import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
  <nav style={{ padding: '1rem 2rem', borderBottom: '1px solid #262626', display: 'flex', gap: '1.5rem', backgroundColor: '#111' }}>
    <a href="/">Home</a>
    <a href="/matches">Matches</a>
    <a href="/teams">Teams</a>
    <a href="/standings">Standings</a>
    <a href="/rivalries">Rivalries</a>
  </nav>
  {children}
</body>
    </html>
  );
}
