/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link'
import { supabase } from '@/lib/supabase'
import { calculateEloWithHistory } from '@/lib/elo'
import { EmptyState, FormIndicator, PageHero, ResultBadge, SectionHeader, StatCard } from '@/components/ui'
import { competitionIdentity, getCompetitionSummary } from '@/lib/competitions'
import { FLOP_RESET_PLAYOFF_TEAMS, normalizePlayoffData, playoffTeamState } from '@/lib/playoffs'
import { formatPublicDate, getSeriesOutcome } from '@/lib/results'
export const dynamic='force-dynamic'

const teamColors:Record<string,string>={Fracture:'#E4A0F7',Frantic:'#AF69EE',Frameshift:'#8F00FF'}
const flopNames:Record<string,string>={'Flop Reset Frameshift':'Frameshift','Flop Reset - Frantic':'Frantic','Flop Reset | Fracture':'Fracture'}
export default async function Home(){
  const [{data:competitions},{data:featured},{data:upcoming},{data:series},{data:teams},{data:stats},{data:leagueMatches},{data:playoffBrackets}]=await Promise.all([
    supabase.from('competitions').select('*'),
    supabase.from('scheduled_matches').select('scheduled_id, opponent_name, match_date, match_time, competition_id, teams ( name, format )').eq('status','scheduled').order('match_date').limit(1).maybeSingle(),
    supabase.from('scheduled_matches').select('scheduled_id, opponent_name, match_date, match_time, competition_id, teams ( name, format )').eq('status','scheduled').order('match_date').limit(3),
    supabase.from('series').select('series_id, competition_id, opponent_name, series_date, notes, teams ( name, format ), matches ( * )').order('series_date',{ascending:false}),
    supabase.from('teams').select('id, name, format, captain, players ( name )').order('name'),
    supabase.from('match_player_stats').select('stat_id, goals, assists, saves, shots, score, players ( name ), matches ( match_date, opponent_name, is_forfeit, teams ( name, format ) )'),
    supabase.from('league_matches').select('round, tier, team_a, team_b, score_a, score_b, status, match_date, format'),
    supabase.from('playoff_brackets').select('*, playoff_matches(*)').order('tier'),
  ])
  const compById=new Map((competitions??[]).map((c:any)=>[c.id,c]))
  const competitionSummaries=new Map((competitions??[]).map((competition:any)=>[competition.id,getCompetitionSummary({competition,series:(series??[]).filter((row:any)=>Number(row.competition_id)===Number(competition.id)),scheduledMatches:(upcoming??[]).filter((row:any)=>Number(row.competition_id)===Number(competition.id))})]))
  const officialSeries=[...competitionSummaries.values()].flatMap((summary)=>summary.officialSeries as any[]).sort((a:any,b:any)=>String(b.series_date??'').localeCompare(String(a.series_date??'')))
  const seriesWins=[...competitionSummaries.values()].reduce((sum,summary)=>sum+summary.seriesWins,0),seriesLosses=[...competitionSummaries.values()].reduce((sum,summary)=>sum+summary.seriesLosses,0),gameWins=[...competitionSummaries.values()].reduce((sum,summary)=>sum+summary.gameWins,0),gameLosses=[...competitionSummaries.values()].reduce((sum,summary)=>sum+summary.gameLosses,0)
  const activePlayers=new Set((teams??[]).flatMap((team:any)=>(team.players??[]).map((p:any)=>p.name))).size
  const groupedTeams=new Map<string,any>()
  ;(teams??[]).forEach((team:any)=>{const current=groupedTeams.get(team.name)??{id:team.name,name:team.name,formats:[],players:[]};if(!current.formats.includes(team.format))current.formats.push(team.format);for(const player of team.players??[]){if(!current.players.some((entry:any)=>entry.name===player.name))current.players.push(player)}groupedTeams.set(team.name,current)})
  const latest=officialSeries[0] as any,latestOutcome=getSeriesOutcome(latest?.matches??[],latest),latestWins=latestOutcome.wins,latestLosses=latestOutcome.losses,latestIsForfeit=latestOutcome.forfeits>0
  const form=officialSeries.slice(0,5).map((s:any)=>{const outcome=getSeriesOutcome(s.matches??[],s);return{id:s.series_id,won:outcome.won,href:`/matches/${s.series_id}`}})
  const power=(['3v3','2v2'] as const).flatMap((format)=>{const data=calculateEloWithHistory((leagueMatches??[]).filter((m:any)=>m.format===format) as any);return data.teamSummaries.filter((t)=>flopNames[t.team]).map((t)=>({...t,short:flopNames[t.team],format}))})
  const career=new Map<string,any>()
  ;(stats??[]).filter((s:any)=>!s.matches?.is_forfeit).forEach((s:any)=>{const name=s.players?.name,format=s.matches?.teams?.format;if(!name||!format)return;const key=`${name}|${format}`,r=career.get(key)??{name,team:s.matches?.teams?.name??'Unknown',format,games:0,goals:0,assists:0,saves:0,shots:0,score:0};r.games++;r.goals+=Number(s.goals??0);r.assists+=Number(s.assists??0);r.saves+=Number(s.saves??0);r.shots+=Number(s.shots??0);r.score+=Number(s.score??0);career.set(key,r)})
  const careerRows=[...career.values()],threshold=Math.max(1,Math.ceil(Math.max(0,...careerRows.map((r)=>r.games))*.2)),eligible=careerRows.filter((r)=>r.games>=threshold)
  const leaderDefs=[['Goals',(r:any)=>r.goals,(v:number)=>String(v)],['Assists',(r:any)=>r.assists,(v:number)=>String(v)],['Saves',(r:any)=>r.saves,(v:number)=>String(v)],['Score / Game',(r:any)=>r.score/r.games,(v:number)=>v.toFixed(0)],['Shooting %',(r:any)=>r.shots?r.goals/r.shots*100:0,(v:number)=>`${v.toFixed(1)}%`]] as const
  const leaders=leaderDefs.map(([label,value,format])=>{const pool=label==='Goals'||label==='Assists'||label==='Saves'?careerRows:eligible;const row=[...pool].filter((r)=>value(r)>0).sort((a,b)=>value(b)-value(a))[0];return{label,row,value:row?format(value(row)):'—'}})
  const teamData=[...groupedTeams.values()].map((team:any)=>{const teamSeries=officialSeries.filter((s:any)=>s.teams?.name===team.name),outcomes=teamSeries.map((s:any)=>({series:s,outcome:getSeriesOutcome(s.matches??[],s)})),wins=outcomes.filter(({outcome}:any)=>outcome.won).length,losses=outcomes.filter(({outcome}:any)=>outcome.lost).length,recent=outcomes.slice(0,5).map(({series:s,outcome}:any)=>({id:s.series_id,won:outcome.won,href:`/matches/${s.series_id}`})),rating=power.filter((p)=>p.short===team.name).sort((a,b)=>(a.overallRank??999)-(b.overallRank??999))[0];return{...team,wins,losses,recent,rating}})
  const recordDefs=[['Goals','goals'],['Assists','assists'],['Saves','saves'],['Shots','shots'],['Score','score']] as const
  const recordEvents:any[]=[]
  for(const[label,key]of recordDefs){let best=0;const byDate=new Map<string,any[]>();(stats??[]).filter((s:any)=>!s.matches?.is_forfeit&&s.matches?.match_date).forEach((s:any)=>{const date=s.matches.match_date.slice(0,10);byDate.set(date,[...(byDate.get(date)??[]),s])});for(const[date,day]of[...byDate.entries()].sort()){const dayBest=Math.max(...day.map((s:any)=>Number(s[key]??0)));if(dayBest>best&&dayBest>0){const setters=day.filter((s:any)=>Number(s[key]??0)===dayBest);recordEvents.push({label,key,value:dayBest,date,players:[...new Set(setters.map((s:any)=>s.players?.name).filter(Boolean))],team:setters[0]?.matches?.teams?.name,format:setters[0]?.matches?.teams?.format,opponent:setters[0]?.matches?.opponent_name,previous:best});best=dayBest}}}
  const latestRecord=recordEvents.sort((a,b)=>b.date.localeCompare(a.date))[0]
  const activeCompetition=(competitions??[]).find((competition:any)=>competition.status==='active'&&competition.format==='3v3')??(competitions??[]).find((competition:any)=>competition.status==='active')
  const activeIdentity=activeCompetition?competitionIdentity(activeCompetition):null
  const activeRawBrackets=(playoffBrackets??[]).filter((bracket:any)=>bracket.competition_id===activeCompetition?.id)
  const activeRawMatches=activeRawBrackets.flatMap((bracket:any)=>bracket.playoff_matches??[])
  const activeBrackets=normalizePlayoffData(activeRawBrackets,activeRawMatches,new Map(),new Map())
  const playoffWatch=FLOP_RESET_PLAYOFF_TEAMS.map((team)=>playoffTeamState(team,activeBrackets))

  return <main className="mx-auto max-w-7xl px-4 py-8 md:px-8 md:py-12">
    <PageHero eyebrow="Competitive Rocket League" title={<>FLOP <span className="text-purple-400">RESET</span></>} description="An esports organization built for competition—and a permanent archive built to remember every team, player, match, and record.">
      <div className="flex flex-wrap gap-2">{teamData.map((team:any)=><Link key={team.id} href={`/teams/${encodeURIComponent(team.name)}`} className="rounded-full border bg-black/30 px-4 py-2 text-sm font-bold text-white no-underline hover:-translate-y-0.5" style={{borderColor:teamColors[team.name]??'#525252'}}>{team.name} · {team.formats.join(' / ')}</Link>)}</div>
      <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard label="Series Record" value={`${seriesWins}–${seriesLosses}`} accent/><StatCard label="Game Record" value={`${gameWins}–${gameLosses}`}/><StatCard label="Teams" value={groupedTeams.size}/><StatCard label="Players" value={activePlayers}/></div>
    </PageHero>

    {activeCompetition&&<section className="mt-12 overflow-hidden rounded-3xl border border-purple-700 bg-[radial-gradient(circle_at_top_right,rgba(143,0,255,.3),transparent_42%),#111] p-6 md:p-9"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="text-xs font-black uppercase tracking-[.24em] text-purple-300">{activeIdentity?.league}</div><h2 className="mt-2 text-3xl font-black text-white md:text-5xl">{activeIdentity?.seasonLabel} Playoffs</h2><p className="mt-2 max-w-2xl text-neutral-400">Live paths for every Flop Reset squad. Bracket advancement is separate from normal match history: BYEs never become games, wins, stats, Elo, or rivalry results.</p></div><Link href={`/competitions/${activeCompetition.id}/playoffs`} className="rounded-xl bg-purple-600 px-5 py-3 text-sm font-black text-white no-underline hover:bg-purple-500">View Playoff Bracket →</Link></div><div className="mt-7 grid gap-3 md:grid-cols-3">{playoffWatch.map((entry)=><div key={entry.team} className="rounded-2xl border border-purple-900/60 bg-black/25 p-5"><div className="flex items-center justify-between gap-3"><div className="text-xl font-black text-white">{entry.team}</div><span className="text-xs font-bold text-purple-300">{entry.status}</span></div><div className="mt-3 text-sm text-neutral-500">{entry.tier} · {entry.round}</div><div className="mt-1 font-semibold text-neutral-300">vs {entry.opponent}</div></div>)}</div></section>}

    <section className="mt-12 grid gap-5 lg:grid-cols-2">
      <div>{featured?<article className="h-full rounded-3xl border border-purple-800 bg-[radial-gradient(circle_at_top_right,rgba(143,0,255,.24),transparent_42%),#111] p-6 md:p-8"><div className="text-xs font-black uppercase tracking-[.2em] text-purple-400">Next Match</div><div className="mt-6 flex flex-col items-center gap-3 text-center sm:flex-row sm:justify-center sm:gap-6"><Link href={`/teams/${encodeURIComponent((featured.teams as any)?.name??'')}`} className="text-3xl font-black text-white hover:underline">{(featured.teams as any)?.name}</Link><span className="text-xl text-neutral-600">VS</span><span className="text-3xl font-black text-neutral-300">{featured.opponent_name??'Opponent TBD'}</span></div><div className="mt-6 text-center text-sm text-neutral-500">{compById.get(featured.competition_id)?.name??'Competition not recorded'} · {(featured.teams as any)?.format}<br/><span className="text-neutral-300">{formatPublicDate(featured.match_date)} {featured.match_time||''}</span></div><Link href="/schedule" className="mt-6 block text-center text-sm font-semibold text-purple-300 hover:underline">Full schedule →</Link></article>:<EmptyState title="No upcoming match scheduled" description="The next fixture will take over this space as soon as it is added." actionHref="/schedule" actionLabel="View schedule"/>}</div>
      <div>{latest?<article className="h-full rounded-3xl border border-neutral-800 bg-[#111] p-6 md:p-8"><div className="text-xs font-black uppercase tracking-[.2em] text-neutral-500">Latest Result</div><div className="mt-5 flex items-center justify-between gap-4"><div><div className="text-3xl font-black text-white">{latest.teams?.name}</div><div className="mt-1 text-lg text-neutral-500">vs {latest.opponent_name}</div></div><div className="text-right"><div className="text-4xl font-black text-purple-300">{latestWins}–{latestLosses}</div><div className="mt-2">{latestIsForfeit?<span className={`rounded-full px-3 py-1 text-sm font-black ${latestOutcome.won?'bg-emerald-950 text-emerald-400':'bg-red-950 text-red-400'}`}>{latestOutcome.result} · FORFEIT</span>:<ResultBadge wins={latestWins} losses={latestLosses}/>}</div></div></div><div className="mt-5 text-sm text-neutral-500">{compById.get(latest.competition_id)?.name??'Competition not recorded'} · {latest.teams?.format} · {formatPublicDate(latest.series_date)}</div><div className="mt-4 flex flex-wrap gap-2">{latest.matches?.map((game:any,index:number)=>{const outcome=getSeriesOutcome([game]);return <span key={game.match_id} className="rounded-lg bg-black/30 px-3 py-2 text-sm text-neutral-400">{game.is_forfeit?'SERIES FORFEIT':`G${index+1}`} · {outcome.result} · {game.is_forfeit?'0–0 · FORFEIT':`${game.flop_reset_score}–${game.opponent_score}`}</span>})}</div><Link href={`/matches/${latest.series_id}`} className="mt-6 inline-block text-sm font-semibold text-purple-300 hover:underline">Open Match Center →</Link></article>:<EmptyState title="No completed series yet" description="The latest result will appear after the first series is recorded."/>}</div>
    </section>

    <section className="mt-16"><SectionHeader eyebrow="Squads" title="Team Showcase" description="Every Flop Reset team appears automatically with its registered formats, roster, record, form, and available Power rating." href="/teams"/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{teamData.map((team:any)=><Link key={team.id} href={`/teams/${encodeURIComponent(team.name)}`} className="group rounded-3xl border border-neutral-800 border-t-4 bg-[#111] p-6 text-white no-underline hover:-translate-y-1 hover:bg-[#151515]" style={{borderTopColor:teamColors[team.name]??'#737373'}}><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-wide text-neutral-500">Flop Reset · {team.formats.join(' / ')}</div><h2 className="mt-1 text-3xl font-black">{team.name}</h2></div><ResultBadge wins={team.wins} losses={team.losses}/></div><div className="mt-5 text-sm text-neutral-500">Roster: {(team.players??[]).slice(0,4).map((p:any)=>p.name).join(' · ')||'Not recorded'}</div><div className="mt-4"><FormIndicator results={team.recent.map((result:any)=>({id:result.id,won:result.won}))}/></div><div className="mt-5 border-t border-neutral-800 pt-4 text-sm text-neutral-500">{team.rating?`#${team.rating.overallRank} overall · ${Math.round(team.rating.rating)} Elo · ${team.rating.tier}`:'Power rating not available yet'}</div></Link>)}</div></section>

    <section className="mt-16 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div><SectionHeader eyebrow="Current form" title="Last Five Series" description="The organization’s most recent competitive results." href="/matches"/><div className="rounded-2xl border border-neutral-800 bg-[#111] p-6"><FormIndicator results={form}/><div className="mt-5 space-y-3">{officialSeries.slice(0,5).map((s:any)=>{const outcome=getSeriesOutcome(s.matches??[],s);return <Link key={s.series_id} href={`/matches/${s.series_id}`} className="flex items-center justify-between gap-3 border-t border-neutral-800 pt-3 text-white no-underline first:border-0 first:pt-0"><div><div className="font-bold">{s.teams?.name} vs {s.opponent_name}</div><div className="text-xs text-neutral-600">{formatPublicDate(s.series_date)} · {s.teams?.format}</div></div><ResultBadge wins={outcome.wins} losses={outcome.losses}/></Link>})}</div></div></div><div><SectionHeader eyebrow="League strength" title="Power Snapshot" href="/power-rankings"/><div className="rounded-2xl border border-neutral-800 bg-[#111] p-5">{power.length?power.sort((a,b)=>(a.overallRank??999)-(b.overallRank??999)).map((p)=><Link key={`${p.team}-${p.format}`} href={`/teams/${encodeURIComponent(p.short)}`} className="flex items-center justify-between border-t border-neutral-800 py-3 text-white no-underline first:border-0"><div><div className="font-bold">{p.short}</div><div className="text-xs text-neutral-600">{p.format} · {p.tier} · {p.matchesTracked} tracked</div></div><div className="text-right"><div className="font-black text-purple-300">#{p.overallRank}</div><div className="text-xs text-neutral-500">{Math.round(p.rating)} Elo</div></div></Link>):<p className="text-sm text-neutral-500">Power Rankings are awaiting the rebuilt league results.</p>}</div></div></section>

    <section className="mt-16"><SectionHeader eyebrow="Player performance" title="Stat Leaders" description={`Career leaders across recorded formats. Rate categories require at least ${threshold} GP.`} href="/stats"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{leaders.map((leader)=><article key={leader.label} className="rounded-2xl border border-neutral-800 bg-[#111] p-5"><div className="text-xs font-bold uppercase tracking-wide text-neutral-500">{leader.label}</div><div className="mt-2 text-3xl font-black text-purple-300">{leader.value}</div>{leader.row?<><Link href={`/players/${encodeURIComponent(leader.row.name)}`} className="mt-3 inline-block font-bold text-white hover:underline">{leader.row.name}</Link><div className="text-xs text-neutral-600">{leader.row.team} · {leader.row.format} · {leader.row.games} GP</div></>:<div className="mt-3 text-sm text-neutral-600">No qualifying player</div>}</article>)}</div></section>

    <section className="mt-16 grid gap-6 lg:grid-cols-2"><div><SectionHeader eyebrow="Record activity" title="Latest Record Activity" href="/records" linkLabel="Record Book"/>{latestRecord?<Link href="/records" className="block rounded-3xl border border-amber-900/40 bg-[radial-gradient(circle_at_top_right,rgba(245,158,11,.12),transparent_45%),#111] p-6 text-white no-underline hover:border-amber-700"><div className="text-xs font-black uppercase tracking-[.2em] text-amber-400">Record Activity</div><div className="mt-3 text-4xl font-black">{latestRecord.value} {latestRecord.label}</div><div className="mt-2 text-xl font-bold text-purple-300">{latestRecord.players.join(' & ')}</div><div className="mt-3 text-sm text-neutral-500">{latestRecord.team} · {latestRecord.format}<br/>vs {latestRecord.opponent} · {formatPublicDate(latestRecord.date)}</div>{latestRecord.previous>0&&<div className="mt-4 border-t border-neutral-800 pt-3 text-xs text-neutral-600">Previous mark: {latestRecord.previous} · +{latestRecord.value-latestRecord.previous}</div>}</Link>:<EmptyState title="No record activity yet" description="A verified record event will appear after competitive player performances are recorded."/>}</div><div><SectionHeader eyebrow="Competitions" title="Current Competition Context" href="/competitions"/><div className="grid gap-3">{(competitions??[]).slice(0,4).map((c:any)=>{const summary=competitionSummaries.get(c.id),count=summary?.officialSeries.length??0,next=summary?.upcomingMatches.length??0;return <Link key={c.id} href={`/competitions/${c.id}`} className="rounded-2xl border border-neutral-800 bg-[#111] p-5 text-white no-underline hover:border-purple-800"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold uppercase text-purple-400">{c.format}</div><div className="mt-1 text-xl font-black">{c.name}</div><div className="text-xs text-neutral-600">{c.host}</div></div><div className="text-right text-sm text-neutral-500">{count} results<br/>{next} upcoming</div></div></Link>})}</div></div></section>

    <section className="mt-16"><SectionHeader eyebrow="Permanent archive" title="History Starts With Every Result" description="Follow the organization from its latest match back through first appearances, rivalries, records, and all-time leaders." href="/history" linkLabel="Enter History"/><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['History','/history'],['Record Book','/records'],['All-Time Leaders','/history/leaders'],['Rivalries','/rivalries'],['Transactions','/transactions']].map(([label,href])=><Link key={href} href={href} className="rounded-xl border border-neutral-800 bg-[#111] p-4 text-center font-bold text-white no-underline hover:border-purple-800 hover:bg-purple-950/20">{label}</Link>)}</div></section>
  </main>
}
