/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link'
import { supabase } from '@/lib/supabase'
import { calculateEloWithHistory } from '@/lib/elo'
import { EmptyState, FormIndicator, PageHero, ResultBadge, SectionHeader, StatCard } from '@/components/ui'
import { competitionIdentity, getCompetitionSummary } from '@/lib/competitions'
import { normalizePlayoffData, playoffTeamState, shortFlopTeam } from '@/lib/playoffs'
import { formatPublicDate, getSeriesOutcome } from '@/lib/results'
import { fetchAllPages } from '@/lib/paginatedQuery'
import { teamHref } from '@/lib/teamRoutes'
import { phaseIsPowerEvidence } from '@/lib/competitionPhase'
import { brandingForTeam } from '@/lib/teamBranding'
import { isCurrentTeam } from '@/lib/teamLifecycle'
import { groupCompetitionsBySeason } from '@/lib/seasons'
import { buildCurrentRosterContexts } from '@/lib/currentRosters'
import { lifecycleLabel, operationalCompetitionIds, rowsForCompetitionIds, selectOperationalCompetition, selectOperationalSeason } from '@/lib/fallOperations'
import { ScheduledMatchCard } from '@/components/ScheduledMatchCard'
export const dynamic='force-dynamic'

export default async function Home(){
  const [{data:competitions},{data:upcoming},{data:series},{data:teams},{data:stats},{data:leagueMatches},{data:playoffBrackets},{data:competitionEntries},{data:seasons},{data:competitionRosters}]=await Promise.all([
    supabase.from('competitions').select('*'),
    supabase.from('scheduled_matches').select('scheduled_id, opponent_name, match_date, scheduled_local_time, match_time, timezone, best_of, competition_phase, stage_label, tier, source_url, competition_id, teams ( id, name, format )').eq('status','scheduled').order('match_date').order('scheduled_local_time').limit(3),
    fetchAllPages((from,to)=>supabase.from('series').select('series_id, competition_id, opponent_name, series_date, notes, teams ( id, name, format ), matches ( * )').order('series_date',{ascending:false}).range(from,to)).then(data=>({data})),
    supabase.from('teams').select('id, name, format, display_name, short_name, slug, primary_color, secondary_color, logo_url, wordmark_style, active, brand_metadata').order('name'),
    fetchAllPages((from,to)=>supabase.from('match_player_stats').select('stat_id, goals, assists, saves, shots, score, players ( name ), matches ( match_date, opponent_name, is_forfeit, teams ( id, name, format ) )').range(from,to)).then(data=>({data})),
    fetchAllPages((from,to)=>supabase.from('league_matches').select('competition_id, competition_phase, round, tier, team_a, team_b, score_a, score_b, status, match_date, format').range(from,to)).then(data=>({data})),
    supabase.from('playoff_brackets').select('*, playoff_matches(*)').neq('status','hidden').order('tier'),
    supabase.from('public_competition_entries').select('entry_id, competition_id, fr_team_id, display_name_snapshot, tier, registration_status, status'),
    supabase.from('public_competition_seasons').select('*').order('season_year',{ascending:false}),
    supabase.from('public_competition_roster_members').select('roster_member_id, entry_id, display_name_snapshot, role, is_current, status, league_player_slug, league_player_display_name'),
  ])
  const compById=new Map((competitions??[]).map((c:any)=>[c.id,c]))
  const competitionSummaries=new Map((competitions??[]).map((competition:any)=>[competition.id,getCompetitionSummary({competition,series:(series??[]).filter((row:any)=>Number(row.competition_id)===Number(competition.id)),scheduledMatches:(upcoming??[]).filter((row:any)=>Number(row.competition_id)===Number(competition.id))})]))
  const seasonGroups=groupCompetitionsBySeason(competitions??[],seasons??[]),operationalSeason=selectOperationalSeason(seasonGroups),operationalIds=operationalCompetitionIds(operationalSeason),completedSeason=seasonGroups.find((season)=>season.status==='completed'||season.status==='archived')
  const completedCompetitionIds=new Set(completedSeason?.competitions.map((competition)=>Number(competition.id))??[])
  const completedSeries=(series??[]).filter((row:any)=>completedCompetitionIds.has(Number(row.competition_id)))
  const completedTeamCount=new Set(completedSeries.map((row:any)=>Number(row.teams?.id)).filter(Number.isFinite)).size
  const officialSeries=[...competitionSummaries.values()].flatMap((summary)=>summary.officialSeries as any[]).sort((a:any,b:any)=>String(b.series_date??'').localeCompare(String(a.series_date??'')))
  const currentSeries=rowsForCompetitionIds(officialSeries,operationalIds),currentUpcoming=rowsForCompetitionIds(upcoming??[],operationalIds),currentSummaries=[...competitionSummaries.entries()].filter(([id])=>operationalIds.has(Number(id))).map(([,summary])=>summary)
  const seriesWins=currentSummaries.reduce((sum,summary)=>sum+summary.seriesWins,0),seriesLosses=currentSummaries.reduce((sum,summary)=>sum+summary.seriesLosses,0),gameWins=currentSummaries.reduce((sum,summary)=>sum+summary.gameWins,0),gameLosses=currentSummaries.reduce((sum,summary)=>sum+summary.gameLosses,0)
  const currentTeams=(teams??[]).filter(isCurrentTeam)
  const currentTeamIds=new Set(currentTeams.map((team:any)=>Number(team.id)))
  const currentRosters=buildCurrentRosterContexts({teams:currentTeams,seasons:seasons??[],competitions:competitions??[],entries:competitionEntries??[],members:competitionRosters??[]})
  const activePlayers=new Set([...currentRosters.values()].flatMap((context)=>context.members.map((member)=>member.display_name_snapshot))).size
  const groupedTeams=new Map<number,any>()
  ;currentTeams.forEach((team:any)=>{groupedTeams.set(Number(team.id),{id:Number(team.id),name:team.name,formats:[team.format],players:currentRosters.get(Number(team.id))?.members??[],brand:brandingForTeam(team)})})
  const featured=currentUpcoming[0] as any,latest=currentSeries[0] as any,latestOutcome=getSeriesOutcome(latest?.matches??[],latest),latestWins=latestOutcome.wins,latestLosses=latestOutcome.losses,latestIsForfeit=latestOutcome.forfeits>0
  const form=currentSeries.slice(0,5).map((s:any)=>{const outcome=getSeriesOutcome(s.matches??[],s);return{id:s.series_id,won:outcome.won,href:`/matches/${s.series_id}`}})
  const activeCompetition=selectOperationalCompetition(operationalSeason,'3v3')??selectOperationalCompetition(operationalSeason)
  const activeEntries=(competitionEntries??[]).filter((entry:any)=>Number(entry.competition_id)===Number(activeCompetition?.id)&&currentTeamIds.has(Number(entry.fr_team_id)))
  const activeEntryNameToTeam=new Map(activeEntries.map((entry:any)=>[String(entry.display_name_snapshot),Number(entry.fr_team_id)]))
  const teamNameById=new Map((teams??[]).map((team:any)=>[Number(team.id),String(team.name)]))
  const power=activeCompetition?calculateEloWithHistory((leagueMatches??[]).filter((match:any)=>Number(match.competition_id)===Number(activeCompetition.id)&&match.format===activeCompetition.format&&phaseIsPowerEvidence(match.competition_phase)) as any).teamSummaries.filter((summary)=>activeEntryNameToTeam.has(summary.team)).map((summary)=>({...summary,teamId:activeEntryNameToTeam.get(summary.team)!,short:teamNameById.get(activeEntryNameToTeam.get(summary.team)!)??summary.team,format:activeCompetition.format})):[]
  const career=new Map<string,any>()
  ;(stats??[]).filter((s:any)=>!s.matches?.is_forfeit).forEach((s:any)=>{const name=s.players?.name,format=s.matches?.teams?.format;if(!name||!format)return;const key=`${name}|${format}`,r=career.get(key)??{name,team:s.matches?.teams?.name??'Unknown',format,games:0,goals:0,assists:0,saves:0,shots:0,score:0};r.games++;r.goals+=Number(s.goals??0);r.assists+=Number(s.assists??0);r.saves+=Number(s.saves??0);r.shots+=Number(s.shots??0);r.score+=Number(s.score??0);career.set(key,r)})
  const careerRows=[...career.values()],threshold=Math.max(1,Math.ceil(Math.max(0,...careerRows.map((r)=>r.games))*.2)),eligible=careerRows.filter((r)=>r.games>=threshold)
  const leaderDefs=[['Goals',(r:any)=>r.goals,(v:number)=>String(v)],['Assists',(r:any)=>r.assists,(v:number)=>String(v)],['Saves',(r:any)=>r.saves,(v:number)=>String(v)],['Score / Game',(r:any)=>r.score/r.games,(v:number)=>v.toFixed(0)],['Shooting %',(r:any)=>r.shots?r.goals/r.shots*100:0,(v:number)=>`${v.toFixed(1)}%`]] as const
  const leaders=leaderDefs.map(([label,value,format])=>{const pool=label==='Goals'||label==='Assists'||label==='Saves'?careerRows:eligible;const row=[...pool].filter((r)=>value(r)>0).sort((a,b)=>value(b)-value(a))[0];return{label,row,value:row?format(value(row)):'—'}})
  const teamData=[...groupedTeams.values()].map((team:any)=>{const teamSeries=currentSeries.filter((s:any)=>Number(s.teams?.id)===team.id),outcomes=teamSeries.map((s:any)=>({series:s,outcome:getSeriesOutcome(s.matches??[],s)})),wins=outcomes.filter(({outcome}:any)=>outcome.won).length,losses=outcomes.filter(({outcome}:any)=>outcome.lost).length,recent=outcomes.slice(0,5).map(({series:s,outcome}:any)=>({id:s.series_id,won:outcome.won,href:`/matches/${s.series_id}`})),rating=power.filter((p)=>p.short===team.name&&p.format===team.formats[0]).sort((a,b)=>(a.overallRank??999)-(b.overallRank??999))[0];return{...team,wins,losses,recent,rating}})
  const recordDefs=[['Goals','goals'],['Assists','assists'],['Saves','saves'],['Shots','shots'],['Score','score']] as const
  const recordEvents:any[]=[]
  for(const[label,key]of recordDefs){let best=0;const byDate=new Map<string,any[]>();(stats??[]).filter((s:any)=>!s.matches?.is_forfeit&&s.matches?.match_date).forEach((s:any)=>{const date=s.matches.match_date.slice(0,10);byDate.set(date,[...(byDate.get(date)??[]),s])});for(const[date,day]of[...byDate.entries()].sort()){const dayBest=Math.max(...day.map((s:any)=>Number(s[key]??0)));if(dayBest>best&&dayBest>0){const setters=day.filter((s:any)=>Number(s[key]??0)===dayBest);recordEvents.push({label,key,value:dayBest,date,players:[...new Set(setters.map((s:any)=>s.players?.name).filter(Boolean))],team:setters[0]?.matches?.teams?.name,format:setters[0]?.matches?.teams?.format,opponent:setters[0]?.matches?.opponent_name,previous:best});best=dayBest}}}
  const latestRecord=recordEvents.sort((a,b)=>b.date.localeCompare(a.date))[0]
  const activeIdentity=activeCompetition?competitionIdentity(activeCompetition):null
  const activeRawBrackets=(playoffBrackets??[]).filter((bracket:any)=>bracket.competition_id===activeCompetition?.id)
  const activeRawMatches=activeRawBrackets.flatMap((bracket:any)=>bracket.playoff_matches??[])
  const activeBrackets=normalizePlayoffData(activeRawBrackets,activeRawMatches,new Map(),new Map())
  const activePlayoffTeams=[...new Set(activeEntries.flatMap((entry:any)=>{const team=shortFlopTeam(entry.display_name_snapshot);return team?[team]:[]}))]
  const playoffWatch=activePlayoffTeams.map((team)=>playoffTeamState(team,activeBrackets))
  const showPlayoffWatch=activeCompetition?.current_stage==='playoffs'&&activeBrackets.length>0
  const operationalEntries=(competitionEntries??[]).filter((entry:any)=>operationalIds.has(Number(entry.competition_id))&&currentTeamIds.has(Number(entry.fr_team_id)))
  const rosterReady=operationalEntries.filter((entry:any)=>currentRosters.get(Number(entry.fr_team_id))?.members.length).length
  const contextCompetitions=[...(operationalSeason?.competitions??[]),...(competitions??[]).filter((competition:any)=>!operationalIds.has(Number(competition.id)))].slice(0,4)

  return <main className="mx-auto max-w-7xl px-4 py-8 md:px-8 md:py-12">
    <PageHero eyebrow="Competitive Rocket League" title={<>FLOP <span className="text-purple-400">RESET</span></>} description="An esports organization built for competition—and a permanent archive built to remember every team, player, match, and record.">
      <div className="flex flex-wrap gap-2">{teamData.map((team:any)=><Link key={team.id} href={teamHref(team)} className="rounded-full border bg-black/30 px-4 py-2 text-sm font-bold text-white no-underline hover:-translate-y-0.5" style={{borderColor:team.brand.secondaryColor}}>{team.brand.shortName} · {team.formats.join(' / ')}</Link>)}</div>
      <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard label={`${operationalSeason?.name??'Current'} Series`} value={`${seriesWins}–${seriesLosses}`} accent/><StatCard label="Game Record" value={`${gameWins}–${gameLosses}`}/><StatCard label="Current Teams" value={groupedTeams.size}/><StatCard label="Registered Players" value={activePlayers}/></div>
    </PageHero>

    {operationalSeason&&<section className="mt-12 overflow-hidden rounded-3xl border border-purple-700/70 bg-[radial-gradient(circle_at_top_right,rgba(168,85,247,.24),transparent_40%),radial-gradient(circle_at_bottom_left,rgba(255,0,166,.12),transparent_42%),#111] p-6 md:p-9"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><div className="text-xs font-black uppercase tracking-[.24em] text-purple-300">{lifecycleLabel(operationalSeason.status)}</div><h2 className="mt-2 text-3xl font-black text-white md:text-5xl">{operationalSeason.name} {operationalSeason.year}</h2><p className="mt-3 max-w-2xl text-neutral-300">Six verified squads are registered for Fall. Rosters and stable Rivalry identities are live; fixtures, results, and Power will unlock from verified competition evidence.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><StatCard label="Formats" value={operationalSeason.competitions.length}/><StatCard label="Entries" value={operationalEntries.length}/><StatCard label="Rosters Ready" value={`${rosterReady}/${operationalEntries.length}`}/><StatCard label="Scheduled" value={currentUpcoming.length}/></div></div><div className="flex flex-wrap gap-3">{operationalSeason.competitions.map((competition:any)=><Link key={competition.id} href={`/competitions/${competition.id}`} className="rounded-xl bg-purple-600 px-5 py-3 text-sm font-black text-white no-underline hover:bg-purple-500">Open {competition.format} hub →</Link>)}</div></div></section>}

    {completedSeason&&<section className="mt-12 overflow-hidden rounded-3xl border border-emerald-900/70 bg-[radial-gradient(circle_at_top_right,rgba(16,185,129,.16),transparent_42%),#111] p-6 md:p-9"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="text-xs font-black uppercase tracking-[.24em] text-emerald-400">Completed Competition</div><h2 className="mt-2 text-3xl font-black text-white md:text-5xl">{completedSeason.name} {completedSeason.year}</h2><p className="mt-3 max-w-2xl text-neutral-400">The first permanent chapter of Flop Reset history is archived with its format-specific results, teams, rosters, leaders, placements, awards, and playoff record.</p><div className="mt-5 flex flex-wrap gap-4 text-sm text-neutral-500"><span>{completedSeason.competitions.length} formats</span><span>{completedTeamCount} Flop Reset teams</span><span>{completedSeries.length} recorded series</span></div></div><Link href={`/competitions/archive/${completedSeason.slug}`} className="inline-flex min-w-max rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white no-underline hover:bg-emerald-500">Open the season archive →</Link></div></section>}

    {showPlayoffWatch&&<section className="mt-12 overflow-hidden rounded-3xl border border-[#FF00A6]/70 bg-[radial-gradient(circle_at_top_right,rgba(255,0,166,.2),transparent_42%),#111] p-6 md:p-9"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="text-xs font-black uppercase tracking-[.24em] text-[#42D7C0]">{activeIdentity?.league}</div><h2 className="mt-2 text-3xl font-black text-white md:text-5xl">{activeIdentity?.seasonLabel} Playoffs</h2><p className="mt-2 max-w-2xl text-neutral-400">Live paths for every registered Flop Reset squad. BYEs never become games, wins, stats, Power evidence, or rivalry results.</p></div><Link href={`/competitions/${activeCompetition.id}/playoffs`} className="rounded-xl bg-[#FF00A6] px-5 py-3 text-sm font-black text-white no-underline hover:brightness-110">View Playoff Bracket →</Link></div><div className="mt-7 grid gap-3 md:grid-cols-3">{playoffWatch.map((entry)=><div key={entry.team} className="rounded-2xl border border-[#FF00A6]/40 bg-black/25 p-5"><div className="flex items-center justify-between gap-3"><div className="text-xl font-black text-white">{entry.team}</div><span className="text-xs font-bold text-[#42D7C0]">{entry.status}</span></div><div className="mt-3 text-sm text-neutral-500">{entry.tier} · {entry.round}</div><div className="mt-1 font-semibold text-neutral-300">vs {entry.opponent}</div></div>)}</div></section>}

    <section className="mt-12 grid gap-5 lg:grid-cols-2">
      <div>{featured?<div className="h-full rounded-3xl border border-purple-800 bg-[radial-gradient(circle_at_top_right,rgba(143,0,255,.24),transparent_42%),#111] p-4 md:p-5"><div className="mb-3 px-2 text-xs font-black uppercase tracking-[.2em] text-purple-400">Next Match</div><ScheduledMatchCard match={{...featured,competitions:{name:compById.get(featured.competition_id)?.name??'Competition not recorded'}}} featured/><Link href="/schedule" className="mt-4 block text-center text-sm font-semibold text-purple-300 hover:underline">Full schedule →</Link></div>:<EmptyState title="Fall fixtures are pending" description="Rivalry has not generated the opening-week schedule yet. Verified fixtures will appear here without manual guessing." actionHref="/schedule" actionLabel="Open Match Center"/>}</div>
      <div>{latest?<article className="h-full rounded-3xl border border-neutral-800 bg-[#111] p-6 md:p-8"><div className="text-xs font-black uppercase tracking-[.2em] text-neutral-500">Latest Fall Result</div><div className="mt-5 flex items-center justify-between gap-4"><div><div className="text-3xl font-black text-white">{latest.teams?.name}</div><div className="mt-1 text-lg text-neutral-500">vs {latest.opponent_name}</div></div><div className="text-right"><div className="text-4xl font-black text-purple-300">{latestWins}–{latestLosses}</div><div className="mt-2">{latestIsForfeit?<span className={`rounded-full px-3 py-1 text-sm font-black ${latestOutcome.won?'bg-emerald-950 text-emerald-400':'bg-red-950 text-red-400'}`}>{latestOutcome.result} · FORFEIT</span>:<ResultBadge wins={latestWins} losses={latestLosses}/>}</div></div></div><div className="mt-5 text-sm text-neutral-500">{compById.get(latest.competition_id)?.name??'Competition not recorded'} · {latest.teams?.format} · {formatPublicDate(latest.series_date)}</div><div className="mt-4 flex flex-wrap gap-2">{latest.matches?.map((game:any,index:number)=>{const outcome=getSeriesOutcome([game]);return <span key={game.match_id} className="rounded-lg bg-black/30 px-3 py-2 text-sm text-neutral-400">{game.is_forfeit?'SERIES FORFEIT':`G${index+1}`} · {outcome.result} · {game.is_forfeit?'0–0 · FORFEIT':`${game.flop_reset_score}–${game.opponent_score}`}</span>})}</div><Link href={`/matches/${latest.series_id}`} className="mt-6 inline-block text-sm font-semibold text-purple-300 hover:underline">Open Match Center →</Link></article>:<EmptyState title="Opening result awaiting play" description="Fall starts at a clean 0–0. Summer results remain in the archive instead of filling the live-season card." actionHref={completedSeason?`/competitions/archive/${completedSeason.slug}`:'/history'} actionLabel="Browse Summer history"/>}</div>
    </section>

    <section className="mt-16"><SectionHeader eyebrow="Current squads" title="Team Showcase" description="Every active Flop Reset team appears with its verified current-season roster, record, form, branding, and available Power rating." href="/teams"/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{teamData.map((team:any)=><Link key={team.id} href={teamHref(team)} className="group rounded-3xl border border-neutral-800 border-t-4 bg-[#111] p-6 text-white no-underline hover:-translate-y-1 hover:bg-[#151515]" style={{borderTopColor:team.brand.secondaryColor,backgroundImage:`linear-gradient(135deg, ${team.brand.primaryColor}18, transparent 48%)`}}><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-wide text-neutral-500">Flop Reset · {team.formats.join(' / ')}</div><h2 className="mt-1 text-3xl font-black">{team.brand.name}</h2></div><ResultBadge wins={team.wins} losses={team.losses}/></div><div className="mt-5 text-sm text-neutral-500">Roster: {(team.players??[]).slice(0,4).map((p:any)=>p.display_name_snapshot).join(' · ')||'Coming soon'}</div><div className="mt-4"><FormIndicator results={team.recent.map((result:any)=>({id:result.id,won:result.won}))}/></div><div className="mt-5 border-t border-neutral-800 pt-4 text-sm text-neutral-500">{team.rating?`#${team.rating.overallRank} overall · ${Math.round(team.rating.rating)} Elo · ${team.rating.tier}`:'Power rating not available yet'}</div></Link>)}</div></section>

    <section className="mt-16 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div><SectionHeader eyebrow="Fall form" title="Last Five Series" description="Only the current Fall season appears here. Summer form remains archived." href="/matches"/><div className="rounded-2xl border border-neutral-800 bg-[#111] p-6"><FormIndicator results={form}/><div className="mt-5 space-y-3">{currentSeries.slice(0,5).map((s:any)=>{const outcome=getSeriesOutcome(s.matches??[],s);return <Link key={s.series_id} href={`/matches/${s.series_id}`} className="flex items-center justify-between gap-3 border-t border-neutral-800 pt-3 text-white no-underline first:border-0 first:pt-0"><div><div className="font-bold">{s.teams?.name} vs {s.opponent_name}</div><div className="text-xs text-neutral-600">{formatPublicDate(s.series_date)} · {s.teams?.format}</div></div><ResultBadge wins={outcome.wins} losses={outcome.losses}/></Link>})}{!currentSeries.length&&<p className="text-sm text-neutral-500">Fall form begins with the first verified series.</p>}</div></div></div><div><SectionHeader eyebrow="Fresh rating pool" title="Fall Power" href="/power-rankings"/><div className="rounded-2xl border border-neutral-800 bg-[#111] p-5">{power.length?power.sort((a,b)=>(a.overallRank??999)-(b.overallRank??999)).map((p)=><Link key={`${p.team}-${p.format}`} href={teamHref({id:p.teamId})} className="flex items-center justify-between border-t border-neutral-800 py-3 text-white no-underline first:border-0"><div><div className="font-bold">{p.short}</div><div className="text-xs text-neutral-600">{p.format} · {p.tier} · {p.matchesTracked} tracked</div></div><div className="text-right"><div className="font-black text-purple-300">#{p.overallRank}</div><div className="text-xs text-neutral-500">{Math.round(p.rating)} Elo</div></div></Link>):<div><div className="font-black text-white">A clean Fall pool</div><p className="mt-2 text-sm text-neutral-500">No Summer rating inheritance and no preseason ranking injection. Rankings begin only after verified Fall results.</p></div>}</div></div></section>

    <section className="mt-16"><SectionHeader eyebrow="Player performance" title="Stat Leaders" description={`Career leaders across recorded formats. Rate categories require at least ${threshold} GP.`} href="/stats"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{leaders.map((leader)=><article key={leader.label} className="rounded-2xl border border-neutral-800 bg-[#111] p-5"><div className="text-xs font-bold uppercase tracking-wide text-neutral-500">{leader.label}</div><div className="mt-2 text-3xl font-black text-purple-300">{leader.value}</div>{leader.row?<><Link href={`/players/${encodeURIComponent(leader.row.name)}`} className="mt-3 inline-block font-bold text-white hover:underline">{leader.row.name}</Link><div className="text-xs text-neutral-600">{leader.row.team} · {leader.row.format} · {leader.row.games} GP</div></>:<div className="mt-3 text-sm text-neutral-600">No qualifying player</div>}</article>)}</div></section>

    <section className="mt-16 grid gap-6 lg:grid-cols-2"><div><SectionHeader eyebrow="Record activity" title="Latest Record Activity" href="/records" linkLabel="Record Book"/>{latestRecord?<Link href="/records" className="block rounded-3xl border border-amber-900/40 bg-[radial-gradient(circle_at_top_right,rgba(245,158,11,.12),transparent_45%),#111] p-6 text-white no-underline hover:border-amber-700"><div className="text-xs font-black uppercase tracking-[.2em] text-amber-400">Record Activity</div><div className="mt-3 text-4xl font-black">{latestRecord.value} {latestRecord.label}</div><div className="mt-2 text-xl font-bold text-purple-300">{latestRecord.players.join(' & ')}</div><div className="mt-3 text-sm text-neutral-500">{latestRecord.team} · {latestRecord.format}<br/>vs {latestRecord.opponent} · {formatPublicDate(latestRecord.date)}</div>{latestRecord.previous>0&&<div className="mt-4 border-t border-neutral-800 pt-3 text-xs text-neutral-600">Previous mark: {latestRecord.previous} · +{latestRecord.value-latestRecord.previous}</div>}</Link>:<EmptyState title="No record activity yet" description="A verified record event will appear after competitive player performances are recorded."/>}</div><div><SectionHeader eyebrow="Competitions" title="Current Competition Context" href="/competitions"/><div className="grid gap-3">{contextCompetitions.map((c:any)=>{const summary=competitionSummaries.get(c.id),count=summary?.officialSeries.length??0,next=summary?.upcomingMatches.length??0;return <Link key={c.id} href={`/competitions/${c.id}`} className="rounded-2xl border border-neutral-800 bg-[#111] p-5 text-white no-underline hover:border-purple-800"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold uppercase text-purple-400">{c.format}</div><div className="mt-1 text-xl font-black">{c.name}</div><div className="text-xs text-neutral-600">{c.host}</div></div><div className="text-right text-sm text-neutral-500">{count} results<br/>{next} upcoming</div></div></Link>})}</div></div></section>

    <section className="mt-16"><SectionHeader eyebrow="Permanent archive" title="History Starts With Every Result" description="Follow the organization from its latest match back through first appearances, rivalries, records, and all-time leaders." href="/history" linkLabel="Enter History"/><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['History','/history'],['Record Book','/records'],['All-Time Leaders','/history/leaders'],['Rivalries','/rivalries'],['Transactions','/transactions']].map(([label,href])=><Link key={href} href={href} className="rounded-xl border border-neutral-800 bg-[#111] p-4 text-center font-bold text-white no-underline hover:border-purple-800 hover:bg-purple-950/20">{label}</Link>)}</div></section>
  </main>
}
