/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from 'next'
import Link from 'next/link'
import { supabase } from '@/lib/supabase'
import { EmptyState, PageHero, ResultBadge, SectionHeader, StatCard } from '@/components/ui'
export const dynamic='force-dynamic'

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const{id}=await params;const{data}=await supabase.from('competitions').select('name, format').eq('id',Number(id)).maybeSingle();return{title:data?`${data.name} — Flop Reset ${data.format}`:'Competition — Flop Reset'}}

export default async function Competition({params}:{params:Promise<{id:string}>}){
  const{id}=await params,competitionId=Number(id)
  const [{data:c},{data:series},{data:upcoming},{data:stats}]=await Promise.all([
    supabase.from('competitions').select('id, name, format, host').eq('id',competitionId).maybeSingle(),
    supabase.from('series').select('series_id, opponent_name, series_date, flop_reset_team_id, teams ( name, format ), matches ( match_id, flop_reset_score, opponent_score, is_forfeit )').eq('competition_id',competitionId).order('series_date',{ascending:false}),
    supabase.from('scheduled_matches').select('scheduled_id, opponent_name, match_date, match_time, teams ( name, format )').eq('competition_id',competitionId).eq('status','scheduled').order('match_date'),
    supabase.from('match_player_stats').select('goals, assists, saves, score, players ( name, teams ( name, format ) ), matches!inner ( competition_id, is_forfeit )').eq('matches.competition_id',competitionId),
  ])
  if(!c)return <main className="mx-auto max-w-5xl px-4 py-16"><EmptyState title="Competition not found" description="This competition is not available in the public archive." actionHref="/competitions" actionLabel="Back to competitions"/></main>
  let seriesWins=0,seriesLosses=0,gameWins=0,gameLosses=0
  ;(series??[]).forEach((s:any)=>{const w=s.matches?.filter((m:any)=>m.flop_reset_score>m.opponent_score).length??0,l=s.matches?.filter((m:any)=>m.flop_reset_score<m.opponent_score).length??0;gameWins+=w;gameLosses+=l;if(w>l)seriesWins++;else if(l>w)seriesLosses++})
  const teams=[...new Set((series??[]).map((s:any)=>s.teams?.name).filter(Boolean))]
  const players=new Map<string,any>();(stats??[]).filter((s:any)=>!s.matches?.is_forfeit).forEach((s:any)=>{const name=s.players?.name;if(!name)return;const r=players.get(name)??{name,team:s.players?.teams?.name??'Unknown',games:0,goals:0,assists:0,saves:0,score:0};r.games++;r.goals+=Number(s.goals??0);r.assists+=Number(s.assists??0);r.saves+=Number(s.saves??0);r.score+=Number(s.score??0);players.set(name,r)})
  const leaders=[...players.values()].sort((a,b)=>b.goals-a.goals).slice(0,5)
  return <main className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14"><PageHero eyebrow={`${c.host||'Competition'} · ${c.format}`} title={c.name} description="Competition hub for Flop Reset results, schedule, participating squads, and player performance."><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard label="Series Record" value={`${seriesWins}–${seriesLosses}`}/><StatCard label="Game Record" value={`${gameWins}–${gameLosses}`}/><StatCard label="Flop Reset Squads" value={teams.length}/><StatCard label="Upcoming" value={upcoming?.length??0}/></div></PageHero>
    <nav className="sticky top-14 z-20 my-8 overflow-x-auto rounded-xl border border-neutral-800 bg-[#0d0d0d]/95 px-4 py-3"><div className="flex min-w-max gap-5 text-xs font-bold uppercase tracking-wide text-neutral-500">{[['overview','Overview'],['schedule','Schedule'],['results','Results'],['leaders','Leaders'],['teams','Teams']].map(([anchor,label])=><a key={anchor} href={`#${anchor}`} className="hover:text-purple-300">{label}</a>)}</div></nav>
    <section id="schedule" className="scroll-mt-28"><SectionHeader eyebrow="Next fixtures" title="Schedule"/>{upcoming?.length?<div className="grid gap-3 md:grid-cols-2">{upcoming.map((m:any)=><article key={m.scheduled_id} className="rounded-2xl border border-neutral-800 bg-[#111] p-5"><div className="text-xs text-neutral-600">{m.match_date} {m.match_time||''} · {m.teams?.format}</div><div className="mt-2 text-lg font-bold text-white">{m.teams?.name} <span className="text-neutral-600">vs</span> {m.opponent_name??'Opponent TBD'}</div></article>)}</div>:<EmptyState title="No upcoming matches" description="No future fixture is currently scheduled for this competition."/>}</section>
    <section id="results" className="mt-14 scroll-mt-28"><SectionHeader eyebrow="Completed series" title="Results"/>{series?.length?<div className="space-y-3">{series.slice(0,10).map((s:any)=>{const w=s.matches?.filter((m:any)=>m.flop_reset_score>m.opponent_score).length??0,l=s.matches?.filter((m:any)=>m.flop_reset_score<m.opponent_score).length??0;return <Link key={s.series_id} href={`/matches/${s.series_id}`} className="flex flex-col justify-between gap-3 rounded-xl border border-neutral-800 bg-[#111] p-4 text-white no-underline hover:border-purple-800 sm:flex-row sm:items-center"><div><div className="text-xs text-neutral-600">{s.series_date} · {s.teams?.format}</div><div className="mt-1 font-bold">{s.teams?.name} vs {s.opponent_name}</div></div><ResultBadge wins={w} losses={l}/></Link>})}</div>:<EmptyState title="No completed series" description="Results will appear after the first recorded series in this competition."/>}</section>
    <section id="leaders" className="mt-14 scroll-mt-28"><SectionHeader eyebrow="Player performance" title="Goals Leaders" description="Non-forfeit player statistics from this competition only."/>{leaders.length?<div className="overflow-x-auto rounded-2xl border border-neutral-800 bg-[#111]"><table className="min-w-[620px] text-sm"><thead><tr className="bg-[#191919] text-left text-xs uppercase text-neutral-500"><th className="px-4 py-3">Rank</th><th className="px-4 py-3">Player</th><th className="px-4 py-3">Team</th><th className="px-4 py-3">GP</th><th className="px-4 py-3">Goals</th><th className="px-4 py-3">G/GP</th></tr></thead><tbody>{leaders.map((p,index)=><tr key={p.name} className="border-t border-neutral-800"><td className="px-4 py-3 text-neutral-600">#{index+1}</td><td className="px-4 py-3"><Link href={`/players/${encodeURIComponent(p.name)}`} className="font-bold text-white hover:underline">{p.name}</Link></td><td className="px-4 py-3 text-neutral-500">{p.team}</td><td className="px-4 py-3">{p.games}</td><td className="px-4 py-3 font-bold text-purple-300">{p.goals}</td><td className="px-4 py-3">{(p.goals/p.games).toFixed(2)}</td></tr>)}</tbody></table></div>:<EmptyState title="No player leaders yet" description="Player statistics have not been recorded for this competition."/>}</section>
    <section id="teams" className="mt-14 scroll-mt-28"><SectionHeader eyebrow="Organization entries" title="Participating Squads"/><div className="flex flex-wrap gap-3">{teams.map((team)=><Link key={team} href={`/teams/${encodeURIComponent(team)}`} className="rounded-full border border-neutral-700 bg-[#111] px-4 py-2 font-bold text-white no-underline hover:border-purple-700">{team}</Link>)}</div></section>
  </main>
}
