/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from 'next'
import Link from 'next/link'
import { supabase } from '@/lib/supabase'
import { EmptyState, ResultBadge, SectionHeader, StatCard } from '@/components/ui'
import { competitionIdentity } from '@/lib/competitions'
import { formatPublicDate, getGameOutcome, getSeriesOutcome } from '@/lib/results'
export const dynamic='force-dynamic'

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const{id}=await params;const{data:s}=await supabase.from('series').select('opponent_name, teams ( name )').eq('series_id',Number(id)).maybeSingle();return{title:s?`${(s.teams as any)?.name} vs ${s.opponent_name} — Flop Reset`:'Match Center — Flop Reset'}}

export default async function MatchCenter({params}:{params:Promise<{id:string}>}){
  const{id}=await params,seriesId=Number(id)
  const{data:series}=await supabase.from('series').select('series_id, competition_id, flop_reset_team_id, opponent_name, series_date, best_of, notes, teams ( name, format ), competitions ( * )').eq('series_id',seriesId).maybeSingle()
  if(!series)return <main className="mx-auto max-w-5xl px-4 py-16"><EmptyState title="Match not found" description="This series is not available in the competitive archive." actionHref="/matches" actionLabel="Back to results"/></main>
  const[{data:games},{data:rivalrySeries},{data:allStats}]=await Promise.all([
    supabase.from('matches').select('*').eq('series_id',seriesId).order('match_id'),
    supabase.from('series').select('series_id, series_date, opponent_name, matches ( * )').eq('flop_reset_team_id',series.flop_reset_team_id).ilike('opponent_name',series.opponent_name).order('series_date',{ascending:false}),
    supabase.from('match_player_stats').select('stat_id, match_id, goals, assists, saves, shots, score, mvp, demos_inflicted, demos_taken, bpm, avg_speed, boost_collected, boost_stolen, players ( name ), matches ( match_date, is_forfeit )'),
  ])
  const gameIds=new Set((games??[]).map((g)=>g.match_id)),playerStats=(allStats??[]).filter((s:any)=>gameIds.has(s.match_id)&&!s.matches?.is_forfeit)
  const seriesOutcome=getSeriesOutcome(games??[]),gamesWon=seriesOutcome.wins,gamesLost=seriesOutcome.losses,isSeriesForfeit=seriesOutcome.forfeits>0
  const competitionContext=series.competitions?competitionIdentity(series.competitions as any):null
  const competitionLabel=competitionContext?`${competitionContext.displayName} ${competitionContext.year} · ${(series.teams as any)?.format??competitionContext.format}`:'Competition not recorded'
  const totals=new Map<string,any>();playerStats.forEach((s:any)=>{const name=s.players?.name??'Unknown',r=totals.get(name)??{name,goals:0,assists:0,saves:0,shots:0,score:0,demos:0,bpm:0,bpmN:0,speed:0,speedN:0};r.goals+=Number(s.goals??0);r.assists+=Number(s.assists??0);r.saves+=Number(s.saves??0);r.shots+=Number(s.shots??0);r.score+=Number(s.score??0);r.demos+=Number(s.demos_inflicted??0);if(s.bpm!=null){r.bpm+=Number(s.bpm);r.bpmN++}if(s.avg_speed!=null){r.speed+=Number(s.avg_speed);r.speedN++}totals.set(name,r)})
  const players=[...totals.values()],seriesScoreLeader=[...players].sort((a,b)=>b.score-a.score)[0]
  const teamGoals=players.reduce((a,p)=>a+p.goals,0),teamShots=players.reduce((a,p)=>a+p.shots,0),teamSaves=players.reduce((a,p)=>a+p.saves,0),teamDemos=players.reduce((a,p)=>a+p.demos,0)
  let rivalryWins=0,rivalryLosses=0,rivalryGameWins=0,rivalryGameLosses=0;(rivalrySeries??[]).forEach((s:any)=>{const outcome=getSeriesOutcome(s.matches??[]);rivalryGameWins+=outcome.wins;rivalryGameLosses+=outcome.losses;if(outcome.won)rivalryWins++;else if(outcome.lost)rivalryLosses++})
  const recordDefs=[['Goals','goals'],['Assists','assists'],['Saves','saves'],['Shots','shots'],['Score','score']] as const
  const records:any[]=[]
  for(const[label,key]of recordDefs){const current=[...playerStats].sort((a:any,b:any)=>Number(b[key]??0)-Number(a[key]??0))[0] as any;if(!current||Number(current[key]??0)<=0)continue;const prior=(allStats??[]).filter((s:any)=>!s.matches?.is_forfeit&&s.matches?.match_date&&s.matches.match_date<series.series_date);const previous=Math.max(0,...prior.map((s:any)=>Number(s[key]??0)));if(Number(current[key])>previous)records.push({label,value:Number(current[key]),player:current.players?.name,previous})}
  const previousMeetings=(rivalrySeries??[]).filter((s:any)=>s.series_id!==seriesId).slice(0,3)
  return <main className="mx-auto max-w-6xl px-4 py-10 md:px-8 md:py-14"><Link href="/matches" className="mb-6 inline-block text-sm text-purple-300 hover:underline">← Back to results</Link>
    <header className={`rounded-3xl border-2 p-6 text-center md:p-10 ${seriesOutcome.won?'border-emerald-700':seriesOutcome.lost?'border-red-700':'border-neutral-700'}`} style={{background:`radial-gradient(circle at top,${seriesOutcome.won?'rgba(16,185,129,.13)':seriesOutcome.lost?'rgba(239,68,68,.13)':'rgba(115,115,115,.13)'},transparent 58%),#101010`}}><div className="text-xs font-black uppercase tracking-[.22em] text-neutral-500">Final · {competitionLabel}{games?.[0]?.round?` · ${games[0].round}`:''}</div><h1 className="mt-7 flex flex-col items-center justify-center gap-4 md:flex-row md:gap-8"><Link href={`/teams/${encodeURIComponent((series.teams as any)?.name??'')}`} className="text-4xl font-black text-white hover:underline md:text-5xl">{(series.teams as any)?.name}</Link><span className="text-5xl font-black text-purple-300">{isSeriesForfeit?'0–0':`${gamesWon}–${gamesLost}`}</span><span className="text-4xl font-black text-neutral-400 md:text-5xl">{series.opponent_name}</span></h1><div className="mt-6 flex justify-center">{isSeriesForfeit?<span className={`rounded-full px-4 py-2 text-sm font-black ${seriesOutcome.won?'bg-emerald-950 text-emerald-300':'bg-red-950 text-red-300'}`}>{seriesOutcome.won?'W':'L'} · FORFEIT</span>:<ResultBadge wins={gamesWon} losses={gamesLost}/>}</div><div className="mt-3 text-sm text-neutral-500">{formatPublicDate(series.series_date)}</div>{series.notes&&<p className="mt-3 text-sm text-neutral-500">{series.notes}</p>}</header>
    {seriesScoreLeader&&<section className="mt-8 grid gap-3 sm:grid-cols-2 md:grid-cols-4"><StatCard label="Series Score Leader" value={<Link href={`/players/${encodeURIComponent(seriesScoreLeader.name)}`} className="text-white hover:underline">{seriesScoreLeader.name}</Link>} detail={`${seriesScoreLeader.score} total score · descriptive, not an award`} accent/><StatCard label="Team Goals" value={teamGoals}/><StatCard label="Team Shooting %" value={teamShots?`${(teamGoals/teamShots*100).toFixed(1)}%`:'—'} detail={`${teamGoals} goals / ${teamShots} shots`}/><StatCard label="Saves / Demos" value={`${teamSaves} / ${teamDemos}`}/></section>}
    {records.length>0&&<section className="mt-12"><SectionHeader eyebrow="Historical impact" title="Records Broken in This Series" description="Compared against every non-forfeit performance recorded before this series date."/><div className="grid gap-4 md:grid-cols-2">{records.map((r)=><Link key={r.label} href="/records" className="rounded-2xl border border-amber-900/50 bg-amber-950/10 p-5 text-white no-underline hover:border-amber-700"><div className="text-xs font-black uppercase text-amber-400">New Flop Reset Record</div><div className="mt-2 text-3xl font-black">{r.value} {r.label}</div><div className="mt-1 text-lg text-purple-300">{r.player}</div><div className="mt-3 text-xs text-neutral-600">Previous mark: {r.previous||'No prior positive mark'}</div></Link>)}</div></section>}
    <section className="mt-12"><SectionHeader eyebrow="Series performance" title="Series Leaders"/>{playerStats.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{([['Goals','goals'],['Assists','assists'],['Saves','saves'],['Score','score']] as const).map(([label,key])=>{const best=[...players].sort((a,b)=>b[key]-a[key])[0];return <article key={key} className="rounded-2xl border border-neutral-800 bg-[#111] p-5"><div className="text-xs font-bold uppercase text-neutral-500">{label}</div><div className="mt-2 text-3xl font-black text-purple-300">{best?.[key]??0}</div>{best&&<Link href={`/players/${encodeURIComponent(best.name)}`} className="mt-2 inline-block font-bold text-white hover:underline">{best.name}</Link>}</article>})}</div>:<EmptyState title="No performance statistics" description={isSeriesForfeit?'No player statistics are generated for a forfeit.':'No player statistics are stored for this series.'}/>}</section>
    <section className="mt-12"><SectionHeader eyebrow="Game breakdown" title="Game by Game" description="Open each game for the full Flop Reset player box score. Forfeits display 0–0 and never fabricate performance rows."/><div className="space-y-4">{games?.map((g,index)=>{const rows=playerStats.filter((s:any)=>s.match_id===g.match_id),game=getGameOutcome(g);return <details key={g.match_id} className="group rounded-2xl border border-neutral-800 bg-[#111]"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5"><div><div className="font-bold text-white">Game {index+1}{g.round?` · ${g.round}`:''}</div><div className="text-xs text-neutral-600">{formatPublicDate(g.match_date)}</div></div><span className={`text-xl font-black ${game.won?'text-emerald-400':game.lost?'text-red-400':'text-neutral-300'}`}>{game.result} · {game.displayScore}{game.isForfeit?' · FORFEIT':''}</span></summary>{game.isForfeit?<div className="border-t border-neutral-800 p-5 text-sm text-neutral-500">No player performance statistics are generated for a forfeit.</div>:<div className="overflow-x-auto border-t border-neutral-800"><table className="min-w-[860px] text-sm"><thead><tr className="bg-[#191919] text-left text-xs uppercase text-neutral-500"><th className="px-4 py-3">Player</th><th>G</th><th>A</th><th>SV</th><th>SH</th><th>SH%</th><th>Score</th><th>Demos</th><th>BPM</th><th>Avg Speed</th></tr></thead><tbody>{rows.map((s:any)=><tr key={s.stat_id} className="border-t border-neutral-800"><td className="px-4 py-3"><Link href={`/players/${encodeURIComponent(s.players?.name)}`} className="font-bold text-white hover:underline">{s.players?.name}</Link>{s.mvp&&<span className="ml-2 text-xs text-purple-400">MVP</span>}</td><td>{s.goals}</td><td>{s.assists}</td><td>{s.saves}</td><td>{s.shots}</td><td>{Number(s.shots)>0?`${(Number(s.goals)/Number(s.shots)*100).toFixed(1)}%`:'—'}</td><td>{s.score}</td><td>{s.demos_inflicted??'—'}</td><td>{s.bpm!=null?Number(s.bpm).toFixed(0):'—'}</td><td>{s.avg_speed!=null?Number(s.avg_speed).toFixed(0):'—'}</td></tr>)}</tbody></table></div>}</details>})}</div></section>
    <section className="mt-12 grid gap-6 lg:grid-cols-2"><div><SectionHeader eyebrow="Opponent context" title={`vs ${series.opponent_name}`}/><div className="rounded-2xl border border-neutral-800 bg-[#111] p-5"><div className="grid grid-cols-2 gap-3"><StatCard label="Series Record" value={`${rivalryWins}–${rivalryLosses}`}/><StatCard label="Game Record" value={`${rivalryGameWins}–${rivalryGameLosses}`}/></div><Link href={`/rivalries/${encodeURIComponent(series.opponent_name)}`} className="mt-4 inline-block text-sm text-purple-300 hover:underline">Explore rivalry history →</Link></div></div><div><SectionHeader eyebrow="Earlier meetings" title="Previous Series"/>{previousMeetings.length?<div className="space-y-3">{previousMeetings.map((s:any)=>{const outcome=getSeriesOutcome(s.matches??[]);return <Link key={s.series_id} href={`/matches/${s.series_id}`} className="flex items-center justify-between rounded-xl border border-neutral-800 bg-[#111] p-4 text-white no-underline hover:border-purple-800"><div className="text-sm"><div className="font-bold">{formatPublicDate(s.series_date)}</div><div className="text-neutral-600">vs {s.opponent_name}</div></div><ResultBadge wins={outcome.wins} losses={outcome.losses}/></Link>})}</div>:<EmptyState title="First recorded meeting" description="No earlier series against this opponent is stored for this squad."/>}</div></section>
  </main>
}
