-- PREPARED ONLY. Review and apply 202608240003 first, backfill every legacy
-- Summer ranking row, then enable its league-match format trigger.

alter table public.league_matches add column if not exists source_name text;
alter table public.league_matches add column if not exists source_match_id text;
alter table public.league_matches add column if not exists team_a_opponent_id bigint references public.opponents(opponent_id);
alter table public.league_matches add column if not exists team_b_opponent_id bigint references public.opponents(opponent_id);

create unique index if not exists league_matches_source_match_unique
  on public.league_matches(competition_id, format, source_name, source_match_id)
  where source_match_id is not null;

create table if not exists public.team_rating_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  competition_id bigint not null references public.competitions(id) on delete cascade,
  format text not null,
  team_name_snapshot text not null,
  opponent_id bigint references public.opponents(opponent_id),
  round_label text not null,
  round_number integer not null,
  match_id bigint references public.league_matches(id) on delete cascade,
  snapshot_date date,
  rating numeric not null,
  overall_rank integer,
  tier_rank integer,
  rating_delta numeric not null default 0,
  model_version text not null,
  created_at timestamptz not null default now(),
  unique (competition_id, format, team_name_snapshot, round_number, match_id, model_version)
);

create index if not exists team_rating_snapshots_pool_round_idx
  on public.team_rating_snapshots(competition_id, format, round_number);
create index if not exists team_rating_snapshots_team_idx
  on public.team_rating_snapshots(team_name_snapshot, competition_id, format);

alter table public.team_rating_snapshots
  add constraint team_rating_snapshots_format_valid
  check (format in ('2v2', '3v3')) not valid;

comment on table public.team_rating_snapshots is
  'Immutable rating output for historical charts, opponent intelligence, and future FR Markets snapshots. Rebuild under a new model_version; never rewrite old market evidence.';
comment on column public.team_rating_snapshots.team_name_snapshot is
  'Historical imported display name. Canonical opponent identity may evolve independently.';
