-- FLOP RESET V2.4 — ARCHIVE FOUNDATION
-- Additive and non-destructive. This migration groups format-specific
-- competitions into permanent seasons and prepares approved seasonal awards.
-- It does not delete results, rewrite rosters, seed brackets, or run imports.

begin;

create table if not exists public.competition_seasons (
  season_id bigint generated by default as identity primary key,
  league_name text not null,
  season_name text not null,
  season_year integer not null,
  slug text not null unique,
  status text not null default 'upcoming',
  starts_at timestamptz,
  ends_at timestamptz,
  summary text,
  hero_image_url text,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('upcoming', 'active', 'completed', 'archived')),
  check (length(trim(league_name)) > 0),
  check (length(trim(season_name)) > 0),
  check (length(trim(slug)) > 0)
);

create unique index if not exists competition_seasons_identity_unique
  on public.competition_seasons (
    lower(trim(league_name)),
    lower(trim(season_name)),
    season_year
  );

alter table public.competitions
  add column if not exists season_id bigint references public.competition_seasons(season_id) on delete restrict;

alter table public.competition_entries add column if not exists regular_season_finish integer;
alter table public.competition_entries add column if not exists final_placement integer;
alter table public.competition_entries add column if not exists placement_label text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.competition_entries'::regclass
      and conname = 'competition_entries_regular_finish_positive'
  ) then
    alter table public.competition_entries
      add constraint competition_entries_regular_finish_positive
      check (regular_season_finish is null or regular_season_finish > 0) not valid;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.competition_entries'::regclass
      and conname = 'competition_entries_final_placement_positive'
  ) then
    alter table public.competition_entries
      add constraint competition_entries_final_placement_positive
      check (final_placement is null or final_placement > 0) not valid;
  end if;
end $$;

create index if not exists competitions_season_idx
  on public.competitions(season_id, format, id);

create table if not exists public.season_awards (
  award_id bigint generated by default as identity primary key,
  season_id bigint not null references public.competition_seasons(season_id) on delete restrict,
  competition_id bigint references public.competitions(id) on delete restrict,
  award_type text not null,
  title text not null,
  recipient_type text not null,
  player_id bigint references public.players(player_id) on delete restrict,
  team_id bigint references public.teams(id) on delete restrict,
  selection_method text not null default 'admin',
  supporting_notes text,
  evidence jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  approved_at timestamptz,
  approved_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (length(trim(award_type)) > 0),
  check (length(trim(title)) > 0),
  check (recipient_type in ('player', 'team', 'organization')),
  check (selection_method in ('statistical', 'admin', 'committee')),
  check (
    (recipient_type = 'player' and player_id is not null and team_id is null)
    or (recipient_type = 'team' and team_id is not null and player_id is null)
    or (recipient_type = 'organization' and player_id is null and team_id is null)
  ),
  check (not is_public or approved_at is not null)
);

create unique index if not exists season_awards_unique_recipient
  on public.season_awards (
    season_id,
    coalesce(competition_id, 0),
    lower(award_type),
    recipient_type,
    coalesce(player_id, 0),
    coalesce(team_id, 0)
  );

create index if not exists season_awards_public_idx
  on public.season_awards(season_id, competition_id, award_type)
  where is_public;

-- Build one season identity for every competition group that already has
-- verified league, circuit, and year values. Summer Circuit 2026 is marked
-- complete from the operator-confirmed conclusion of that event; no result or
-- placement is inferred here.
with grouped as (
  select
    trim(league_name) as league_name,
    trim(circuit_name) as season_name,
    season_year,
    min(starts_at) as starts_at,
    max(ends_at) as ends_at,
    case
      when lower(trim(league_name)) = 'the rivalry'
        and lower(trim(circuit_name)) = 'summer circuit'
        and season_year = 2026 then 'completed'
      when bool_and(coalesce(current_stage, status, 'recorded') in ('completed', 'archived')) then 'completed'
      when bool_or(coalesce(current_stage, status, 'recorded') in ('regular_season', 'playoffs', 'active')) then 'active'
      when bool_and(coalesce(current_stage, status, 'recorded') = 'upcoming') then 'upcoming'
      else 'active'
    end as status
  from public.competitions
  where nullif(trim(league_name), '') is not null
    and nullif(trim(circuit_name), '') is not null
    and season_year is not null
  group by trim(league_name), trim(circuit_name), season_year
), prepared as (
  select
    league_name,
    season_name,
    season_year,
    trim(both '-' from regexp_replace(
      lower(league_name || '-' || season_name || '-' || season_year::text),
      '[^a-z0-9]+', '-', 'g'
    )) as slug,
    status,
    starts_at,
    ends_at
  from grouped
)
insert into public.competition_seasons (
  league_name,
  season_name,
  season_year,
  slug,
  status,
  starts_at,
  ends_at
)
select
  prepared.league_name,
  prepared.season_name,
  prepared.season_year,
  prepared.slug,
  prepared.status,
  prepared.starts_at,
  prepared.ends_at
from prepared
where not exists (
  select 1
  from public.competition_seasons existing
  where lower(trim(existing.league_name)) = lower(trim(prepared.league_name))
    and lower(trim(existing.season_name)) = lower(trim(prepared.season_name))
    and existing.season_year = prepared.season_year
)
on conflict (slug) do nothing;

-- Attach only exact normalized identities. Competitions with incomplete or
-- ambiguous identity remain NULL and are exposed in the admin reconciliation
-- view below rather than being guessed into a season.
update public.competitions c
set season_id = s.season_id
from public.competition_seasons s
where c.season_id is null
  and lower(trim(c.league_name)) = lower(trim(s.league_name))
  and lower(trim(c.circuit_name)) = lower(trim(s.season_name))
  and c.season_year = s.season_year;

alter table public.competition_seasons enable row level security;
alter table public.season_awards enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['competition_seasons', 'season_awards'] loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
        and tablename = table_name
        and policyname = table_name || '_admin_read'
    ) then
      execute format(
        'create policy %I on public.%I for select to authenticated using (coalesce((auth.jwt() -> ''app_metadata'' ->> ''site_admin'')::boolean, false))',
        table_name || '_admin_read', table_name
      );
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
        and tablename = table_name
        and policyname = table_name || '_admin_write'
    ) then
      execute format(
        'create policy %I on public.%I for all to authenticated using (coalesce((auth.jwt() -> ''app_metadata'' ->> ''site_admin'')::boolean, false)) with check (coalesce((auth.jwt() -> ''app_metadata'' ->> ''site_admin'')::boolean, false))',
        table_name || '_admin_write', table_name
      );
    end if;
  end loop;
end $$;

create or replace view public.public_competition_seasons
with (security_barrier = true)
as
select
  season_id,
  league_name,
  season_name,
  season_year,
  slug,
  status,
  starts_at,
  ends_at,
  summary,
  hero_image_url,
  display_order,
  created_at,
  updated_at
from public.competition_seasons;

-- Preserve the existing public view contract and append verified placement
-- fields needed by permanent season archives.
create or replace view public.public_competition_entries
with (security_barrier = true)
as
select
  e.entry_id,
  e.competition_id,
  e.fr_team_id,
  e.opponent_id,
  e.slug,
  e.display_name_snapshot,
  e.logo_url_snapshot,
  e.tier,
  e.seed,
  e.registration_status,
  e.competitive_status,
  e.is_power_tracked,
  e.status,
  e.joined_at,
  e.left_at,
  e.created_at,
  e.updated_at,
  c.name as competition_name,
  c.format as competition_format,
  c.league_name as competition_league_name,
  c.circuit_name as competition_circuit_name,
  c.season_year as competition_season_year,
  c.region as competition_region,
  e.regular_season_finish,
  e.final_placement,
  e.placement_label
from public.competition_entries e
join public.competitions c on c.id = e.competition_id;

create or replace view public.public_season_awards
with (security_barrier = true)
as
select
  a.award_id,
  a.season_id,
  a.competition_id,
  a.award_type,
  a.title,
  a.recipient_type,
  a.player_id,
  a.team_id,
  a.selection_method,
  a.evidence,
  a.approved_at,
  coalesce(p.name, t.display_name, t.name, 'Flop Reset') as recipient_name
from public.season_awards a
left join public.players p on p.player_id = a.player_id
left join public.teams t on t.id = a.team_id
where a.is_public
  and a.approved_at is not null;

create or replace view public.v24_season_reconciliation
with (security_barrier = true)
as
select
  c.id as competition_id,
  c.name,
  c.format,
  c.league_name,
  c.circuit_name,
  c.season_year,
  c.status,
  c.current_stage
from public.competitions c
where c.season_id is null
  and coalesce((auth.jwt() -> 'app_metadata' ->> 'site_admin')::boolean, false);

revoke all on table public.competition_seasons, public.season_awards from anon;
grant select, insert, update, delete on table public.competition_seasons, public.season_awards to authenticated;
grant usage, select on sequence public.competition_seasons_season_id_seq, public.season_awards_award_id_seq to authenticated;
grant select on table public.public_competition_seasons, public.public_season_awards to anon, authenticated;
revoke all on public.v24_season_reconciliation from anon;
grant select on public.v24_season_reconciliation to authenticated;

comment on table public.competition_seasons is
  'Permanent event/season identity grouping format-specific competition rows into one historical chapter.';
comment on column public.competitions.season_id is
  'Stable parent season. NULL means the competition identity requires explicit reconciliation.';
comment on table public.season_awards is
  'Approved permanent season awards. Public visibility requires an approval timestamp.';
comment on column public.competition_entries.final_placement is
  'Verified final placement for this competition entry. NULL means no official placement has been recorded.';
comment on view public.v24_season_reconciliation is
  'Admin-only list of competition rows not yet attached to a permanent season.';

commit;
