-- V2.3.9 LEAGUE DIRECTORY FOUNDATION
-- Schema-only, non-destructive, and safe to apply before any competitive reset.
-- No source data is fetched and no competition entry is seeded by this migration.

begin;

alter table public.competitions add column if not exists league_name text;
alter table public.competitions add column if not exists circuit_name text;
alter table public.competitions add column if not exists season_year integer;
alter table public.competitions add column if not exists region text;
alter table public.competitions add column if not exists status text not null default 'active';
alter table public.competitions add column if not exists starts_at timestamptz;
alter table public.competitions add column if not exists ends_at timestamptz;
alter table public.competitions add column if not exists timezone text;
alter table public.competitions add column if not exists display_metadata jsonb not null default '{}'::jsonb;
alter table public.opponents add column if not exists display_name text;
alter table public.opponents add column if not exists logo_url text;
alter table public.opponents add column if not exists region text;
alter table public.opponents add column if not exists status text not null default 'active';
alter table public.opponents add column if not exists notes text;
alter table public.opponents add column if not exists locked_fields jsonb not null default '[]'::jsonb;
alter table public.opponents add column if not exists updated_by_admin uuid;

create table if not exists public.competition_sources (
  competition_source_id bigint generated by default as identity primary key,
  competition_id bigint not null references public.competitions(id) on delete restrict,
  provider text not null,
  external_competition_id text not null,
  source_url text not null,
  source_status text not null default 'configured',
  parser_version text,
  last_attempted_at timestamptz,
  last_synced_at timestamptz,
  last_successful_sync_at timestamptz,
  last_error text,
  source_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_competition_id),
  unique (competition_id, provider)
);

create table if not exists public.external_team_sources (
  source_id bigint generated by default as identity primary key,
  opponent_id bigint references public.opponents(opponent_id) on delete restrict,
  provider text not null,
  external_team_id text not null,
  source_url text,
  source_display_name text not null,
  mode text,
  region text,
  last_synced_at timestamptz,
  raw_metadata jsonb not null default '{}'::jsonb,
  locked_fields jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_team_id)
);

create table if not exists public.competition_entries (
  entry_id bigint generated by default as identity primary key,
  competition_id bigint not null references public.competitions(id) on delete restrict,
  fr_team_id bigint references public.teams(id) on delete restrict,
  opponent_id bigint references public.opponents(opponent_id) on delete restrict,
  external_source_id bigint references public.external_team_sources(source_id) on delete set null,
  source_registration_key text,
  slug text not null unique,
  display_name_snapshot text not null,
  logo_url_snapshot text,
  tier text,
  seed integer,
  registration_status text not null default 'registered',
  competitive_status text not null default 'pending',
  is_power_tracked boolean not null default false,
  source_provider text,
  source_external_id text,
  source_url text,
  source_values jsonb not null default '{}'::jsonb,
  manual_values jsonb not null default '{}'::jsonb,
  locked_fields jsonb not null default '[]'::jsonb,
  notes text,
  status text not null default 'active',
  joined_at timestamptz,
  left_at timestamptz,
  updated_by_admin uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (num_nonnulls(fr_team_id, opponent_id) <= 1),
  check (
    fr_team_id is not null
    or opponent_id is not null
    or external_source_id is not null
    or source_registration_key is not null
  )
);

create unique index if not exists competition_entries_fr_team_unique
  on public.competition_entries(competition_id, fr_team_id)
  where fr_team_id is not null;
create unique index if not exists competition_entries_opponent_unique
  on public.competition_entries(competition_id, opponent_id)
  where opponent_id is not null;
create unique index if not exists competition_entries_source_registration_unique
  on public.competition_entries(competition_id, source_provider, source_registration_key)
  where source_provider is not null and source_registration_key is not null;

create table if not exists public.league_players (
  league_player_id bigint generated by default as identity primary key,
  slug text not null unique,
  canonical_name text not null,
  normalized_name text not null,
  display_name text,
  linked_fr_player_id bigint references public.players(player_id) on delete restrict,
  status text not null default 'active',
  country text,
  source_provider text,
  source_external_id text,
  source_url text,
  aliases text[] not null default '{}',
  source_values jsonb not null default '{}'::jsonb,
  manual_values jsonb not null default '{}'::jsonb,
  locked_fields jsonb not null default '[]'::jsonb,
  notes text,
  updated_by_admin uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists league_players_source_identity_idx
  on public.league_players(source_provider, source_external_id)
  where source_provider is not null and source_external_id is not null;

create table if not exists public.competition_roster_members (
  roster_member_id bigint generated by default as identity primary key,
  entry_id bigint not null references public.competition_entries(entry_id) on delete restrict,
  league_player_id bigint references public.league_players(league_player_id) on delete restrict,
  source_member_key text not null,
  display_name_snapshot text not null,
  role text not null default 'player',
  status text not null default 'active',
  is_current boolean not null default true,
  source_provider text,
  source_external_id text,
  source_url text,
  source_values jsonb not null default '{}'::jsonb,
  manual_values jsonb not null default '{}'::jsonb,
  locked_fields jsonb not null default '[]'::jsonb,
  joined_at timestamptz,
  left_at timestamptz,
  updated_by_admin uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entry_id, source_member_key)
);

create table if not exists public.external_source_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  competition_source_id bigint references public.competition_sources(competition_source_id) on delete restrict,
  provider text not null,
  source_type text not null,
  source_external_id text not null,
  source_url text not null,
  fetched_at timestamptz not null default now(),
  content_hash text not null,
  parser_version text not null,
  normalized_payload jsonb not null,
  status text not null,
  validation_errors jsonb not null default '[]'::jsonb,
  applied_at timestamptz,
  applied_by uuid,
  unique (provider, source_external_id, content_hash)
);

create table if not exists public.identity_reconciliation_queue (
  reconciliation_id bigint generated by default as identity primary key,
  competition_id bigint references public.competitions(id) on delete restrict,
  entity_type text not null,
  source_provider text,
  source_external_id text,
  source_display_name text not null,
  candidate_entity_type text,
  candidate_entity_id bigint,
  issue_type text not null,
  confidence text not null default 'unknown',
  details jsonb not null default '{}'::jsonb,
  status text not null default 'open',
  resolution_notes text,
  resolved_at timestamptz,
  resolved_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  audit_id bigint generated by default as identity primary key,
  admin_user_id uuid,
  occurred_at timestamptz not null default now(),
  entity_type text not null,
  entity_id text not null,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  reason text,
  source_snapshot_id bigint references public.external_source_snapshots(snapshot_id) on delete set null
);

create table if not exists public.page_content_overrides (
  page_key text primary key,
  title_override text,
  subtitle_override text,
  hero_image_url text,
  featured_content text,
  is_visible boolean not null default true,
  manual_callout text,
  seo_title text,
  seo_description text,
  locked_fields jsonb not null default '[]'::jsonb,
  updated_by_admin uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.playoff_matches add column if not exists competition_entry_a_id bigint references public.competition_entries(entry_id) on delete restrict;
alter table public.playoff_matches add column if not exists competition_entry_b_id bigint references public.competition_entries(entry_id) on delete restrict;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.playoff_matches'::regclass
      and conname = 'playoff_participant_entry_exclusive'
  ) then
    alter table public.playoff_matches
      add constraint playoff_participant_entry_exclusive
      check (
        num_nonnulls(flop_reset_team_a_id, opponent_a_id, competition_entry_a_id) <= 1
        and num_nonnulls(flop_reset_team_b_id, opponent_b_id, competition_entry_b_id) <= 1
      ) not valid;
  end if;
end $$;

create index if not exists competition_entries_competition_idx on public.competition_entries(competition_id, tier, status);
create index if not exists competition_entries_power_idx on public.competition_entries(competition_id, is_power_tracked) where is_power_tracked;
create index if not exists roster_members_entry_idx on public.competition_roster_members(entry_id, is_current);
create index if not exists reconciliation_open_idx on public.identity_reconciliation_queue(status, competition_id);
create index if not exists source_snapshots_lookup_idx on public.external_source_snapshots(provider, source_external_id, fetched_at desc);
create index if not exists audit_entity_idx on public.admin_audit_log(entity_type, entity_id, occurred_at desc);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'competition_sources',
    'external_team_sources',
    'competition_entries',
    'league_players',
    'competition_roster_members',
    'external_source_snapshots',
    'identity_reconciliation_queue',
    'admin_audit_log',
    'page_content_overrides'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = table_name
        and policyname = table_name || '_admin_read'
    ) then
      execute format(
        'create policy %I on public.%I for select to authenticated using (coalesce((auth.jwt() -> ''app_metadata'' ->> ''site_admin'')::boolean, false))',
        table_name || '_admin_read', table_name
      );
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = table_name
        and policyname = table_name || '_admin_write'
    ) then
      execute format(
        'create policy %I on public.%I for all to authenticated using (coalesce((auth.jwt() -> ''app_metadata'' ->> ''site_admin'')::boolean, false)) with check (coalesce((auth.jwt() -> ''app_metadata'' ->> ''site_admin'')::boolean, false))',
        table_name || '_admin_write', table_name
      );
    end if;
  end loop;
end $$;

-- Public pages use deliberately narrow projections. The base tables remain
-- admin-only so notes, manual values, lock state, reconciliation evidence,
-- and admin identifiers cannot leak through PostgREST.
create or replace view public.public_competition_entries
with (security_barrier = true)
as
select
  e.entry_id,
  e.competition_id,
  e.fr_team_id,
  e.opponent_id,
  e.slug,
  e.display_name_snapshot,
  e.logo_url_snapshot,
  e.tier,
  e.seed,
  e.registration_status,
  e.competitive_status,
  e.is_power_tracked,
  e.status,
  e.joined_at,
  e.left_at,
  e.created_at,
  e.updated_at,
  c.name as competition_name,
  c.format as competition_format,
  c.league_name as competition_league_name,
  c.circuit_name as competition_circuit_name,
  c.season_year as competition_season_year,
  c.region as competition_region
from public.competition_entries e
join public.competitions c on c.id = e.competition_id;

create or replace view public.public_league_players
with (security_barrier = true)
as
select
  league_player_id,
  slug,
  canonical_name,
  display_name,
  linked_fr_player_id,
  status,
  country,
  aliases,
  created_at,
  updated_at
from public.league_players;

create or replace view public.public_competition_roster_members
with (security_barrier = true)
as
select
  r.roster_member_id,
  r.entry_id,
  r.league_player_id,
  r.display_name_snapshot,
  r.role,
  r.status,
  r.is_current,
  r.source_url,
  r.joined_at,
  r.left_at,
  r.created_at,
  r.updated_at,
  e.competition_id,
  e.slug as entry_slug,
  e.display_name_snapshot as entry_display_name,
  e.tier as entry_tier,
  lp.slug as league_player_slug,
  lp.display_name as league_player_display_name,
  c.name as competition_name,
  c.format as competition_format,
  c.league_name as competition_league_name,
  c.circuit_name as competition_circuit_name,
  c.season_year as competition_season_year,
  c.region as competition_region
from public.competition_roster_members r
join public.competition_entries e on e.entry_id = r.entry_id
join public.competitions c on c.id = e.competition_id
left join public.league_players lp on lp.league_player_id = r.league_player_id;

create or replace view public.public_page_content_overrides
with (security_barrier = true)
as
select
  page_key,
  title_override,
  subtitle_override,
  hero_image_url,
  featured_content,
  is_visible,
  manual_callout,
  seo_title,
  seo_description,
  created_at,
  updated_at
from public.page_content_overrides;

revoke all on table
  public.competition_sources,
  public.external_team_sources,
  public.competition_entries,
  public.league_players,
  public.competition_roster_members,
  public.external_source_snapshots,
  public.identity_reconciliation_queue,
  public.admin_audit_log,
  public.page_content_overrides
from anon;

grant select, insert, update, delete on table
  public.competition_sources,
  public.external_team_sources,
  public.competition_entries,
  public.league_players,
  public.competition_roster_members,
  public.external_source_snapshots,
  public.identity_reconciliation_queue,
  public.admin_audit_log,
  public.page_content_overrides
to authenticated;

grant select on table
  public.public_competition_entries,
  public.public_league_players,
  public.public_competition_roster_members,
  public.public_page_content_overrides
to anon, authenticated;

comment on table public.competition_entries is 'Authoritative competition-scoped participant directory. Tier and registration state belong here, not on timeless team identity.';
comment on column public.competition_entries.source_registration_key is 'Competition-scoped idempotency key. It is not proof of canonical team identity.';
comment on table public.competition_roster_members is 'Event roster history. Removal closes a membership row instead of deleting it.';
comment on table public.external_source_snapshots is 'Last-good normalized source evidence. Public pages never fetch Rivalry directly.';
comment on table public.identity_reconciliation_queue is 'Human review queue. Name similarity never authorizes an automatic canonical merge.';

commit;
