-- FLOP RESET CORE SCHEMA BASELINE
--
-- Reconstructs the empty schema that predates the checked-in migration
-- history. This file contains structure, constraints, indexes, grants, and
-- RLS only. It deliberately contains no teams, players, competitions,
-- results, brackets, source snapshots, or other historical/test data.
--
-- On the original production database these relations already exist, so the
-- IF NOT EXISTS guards make this migration a no-op for the tables themselves.
-- It is intended primarily for a fresh Supabase project before 001-005 and
-- 009-015 are applied in filename order.

begin;

create table if not exists public.competitions (
  name text not null,
  host text not null,
  format text not null,
  external_url text not null,
  id bigint generated by default as identity primary key,
  country text
);

create table if not exists public.teams (
  name text not null,
  format text not null,
  captain text,
  id bigint generated by default as identity primary key,
  constraint teams_name_format_unique unique (name, format)
);

create table if not exists public.players (
  player_id bigint generated by default as identity primary key,
  name text not null,
  team_id bigint references public.teams(id),
  aliases text[] default '{}'::text[],
  status text default 'active',
  retired_at date,
  constraint players_status_check
    check (status in ('active', 'inactive', 'departed', 'retired'))
);

create table if not exists public.seasons (
  season_id bigint generated by default as identity primary key,
  name text not null,
  start_date date,
  end_date date
);

create table if not exists public.opponents (
  opponent_id bigint generated by default as identity primary key,
  canonical_name text not null,
  normalized_name text unique,
  country text,
  created_at timestamptz not null default now()
);

create table if not exists public.opponent_aliases (
  alias_id bigint generated by default as identity primary key,
  opponent_id bigint not null references public.opponents(opponent_id) on delete cascade,
  alias text not null,
  normalized_alias text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.player_team_memberships (
  membership_id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(player_id) on delete restrict,
  team_id bigint not null references public.teams(id) on delete restrict,
  joined_at date,
  left_at date,
  status text not null default 'active',
  role text default 'player',
  source text,
  notes text,
  created_at timestamptz not null default now(),
  constraint player_team_memberships_dates_valid
    check (left_at is null or joined_at is null or left_at >= joined_at),
  constraint player_team_memberships_status_valid
    check (status in ('active', 'inactive', 'departed', 'retired'))
);

create table if not exists public.series (
  series_id bigint generated by default as identity primary key,
  competition_id bigint references public.competitions(id),
  flop_reset_team_id bigint references public.teams(id),
  opponent_name text not null,
  best_of integer default 5,
  series_date date not null,
  notes text,
  season_id bigint references public.seasons(season_id),
  opponent_id bigint references public.opponents(opponent_id) on delete set null
);

create table if not exists public.matches (
  match_id bigint generated by default as identity primary key,
  competition_id bigint references public.competitions(id),
  flop_reset_team_id bigint references public.teams(id),
  opponent_name text not null,
  flop_reset_score integer not null,
  opponent_score integer not null,
  is_forfeit boolean default false,
  match_date date not null,
  replay_url text,
  notes text,
  created_at timestamptz default now(),
  series_id bigint references public.series(series_id),
  round text,
  replay_id text,
  played_at timestamptz,
  game_number integer,
  result_note text
);

create unique index if not exists matches_replay_id_unique
  on public.matches(replay_id) where replay_id is not null;

create table if not exists public.match_player_stats (
  stat_id bigint generated by default as identity primary key,
  match_id bigint references public.matches(match_id),
  player_id bigint references public.players(player_id),
  goals integer default 0,
  assists integer default 0,
  saves integer default 0,
  shots integer default 0,
  score integer default 0,
  mvp boolean default false,
  bpm integer,
  avg_speed integer,
  time_supersonic numeric,
  time_on_ground numeric,
  time_low_air numeric,
  time_high_air numeric,
  time_defensive_third numeric,
  time_neutral_third numeric,
  time_offensive_third numeric,
  demos_taken integer,
  boost_collected integer,
  boost_stolen integer,
  zero_boost_time numeric,
  demos_inflicted integer,
  percentage_most_back numeric,
  percentage_most_forward numeric,
  percentage_behind_ball numeric,
  percentage_in_front_of_ball numeric,
  percentage_defensive_half numeric,
  percentage_offensive_half numeric,
  avg_distance_to_ball numeric,
  avg_distance_to_ball_has_possession numeric,
  avg_distance_to_ball_no_possession numeric,
  avg_distance_to_teammates numeric,
  zero_boost_pct numeric,
  percentage_supersonic_speed numeric,
  percentage_on_ground numeric,
  percentage_low_air numeric,
  percentage_high_air numeric,
  percentage_defensive_third numeric,
  percentage_neutral_third numeric,
  percentage_offensive_third numeric
);

create table if not exists public.league_matches (
  id bigint generated by default as identity primary key,
  format text not null,
  round text not null,
  tier text not null,
  team_a text not null,
  team_b text,
  score_a text,
  score_b text,
  status text not null,
  match_date date,
  created_at timestamptz default now(),
  batch_label text
);

create table if not exists public.scheduled_matches (
  scheduled_id bigint generated by default as identity primary key,
  competition_id bigint references public.competitions(id),
  flop_reset_team_id bigint references public.teams(id),
  opponent_name text,
  match_date date not null,
  match_time text,
  status text default 'scheduled',
  notes text,
  created_at timestamptz default now(),
  starts_at timestamptz,
  opponent_id bigint references public.opponents(opponent_id) on delete set null
);

create table if not exists public.playoff_brackets (
  bracket_id bigint generated by default as identity primary key,
  competition_id bigint not null references public.competitions(id) on delete cascade,
  tier text not null,
  name text,
  status text not null default 'upcoming',
  starts_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint playoff_brackets_competition_tier_unique unique (competition_id, tier),
  constraint playoff_brackets_status_valid
    check (status in ('upcoming', 'active', 'completed', 'archived', 'hidden'))
);

create table if not exists public.playoff_matches (
  playoff_match_id bigint generated by default as identity primary key,
  bracket_id bigint not null references public.playoff_brackets(bracket_id) on delete cascade,
  round_name text not null,
  round_order integer not null,
  match_order integer not null,
  slot1_team_id bigint references public.teams(id) on delete set null,
  slot1_opponent_id bigint references public.opponents(opponent_id) on delete set null,
  slot1_name_snapshot text,
  slot2_team_id bigint references public.teams(id) on delete set null,
  slot2_opponent_id bigint references public.opponents(opponent_id) on delete set null,
  slot2_name_snapshot text,
  slot1_score integer,
  slot2_score integer,
  winner_side integer,
  status text not null default 'tbd',
  best_of integer,
  scheduled_at timestamptz,
  is_bye boolean not null default false,
  is_forfeit boolean not null default false,
  series_id bigint references public.series(series_id) on delete set null,
  scheduled_match_id bigint references public.scheduled_matches(scheduled_id) on delete set null,
  next_match_id bigint references public.playoff_matches(playoff_match_id) on delete set null,
  next_slot integer,
  loser_next_match_id bigint references public.playoff_matches(playoff_match_id) on delete set null,
  loser_next_slot integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint playoff_matches_bracket_round_match_unique
    unique (bracket_id, round_order, match_order),
  constraint playoff_matches_status_valid
    check (status in ('tbd', 'scheduled', 'live', 'final')),
  constraint playoff_matches_winner_side_valid
    check (winner_side is null or winner_side in (1, 2)),
  constraint playoff_matches_next_slot_valid
    check (next_slot is null or next_slot in (1, 2)),
  constraint playoff_matches_loser_next_slot_valid
    check (loser_next_slot is null or loser_next_slot in (1, 2))
);

create index if not exists idx_player_memberships_player
  on public.player_team_memberships(player_id);
create index if not exists idx_player_memberships_team
  on public.player_team_memberships(team_id);
create index if not exists idx_series_opponent
  on public.series(opponent_id);
create index if not exists idx_scheduled_opponent
  on public.scheduled_matches(opponent_id);
create index if not exists idx_playoff_bracket_competition
  on public.playoff_brackets(competition_id);
create index if not exists idx_playoff_match_bracket
  on public.playoff_matches(bracket_id);
create index if not exists idx_playoff_match_series
  on public.playoff_matches(series_id);

-- Tables covered by later migrations intentionally receive their policies
-- there. These baseline-only tables need equivalent public-read/site-admin
-- write protection here.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'seasons', 'opponents', 'opponent_aliases',
    'player_team_memberships', 'scheduled_matches'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
        and tablename = table_name
        and policyname = table_name || '_public_read'
    ) then
      execute format(
        'create policy %I on public.%I for select using (true)',
        table_name || '_public_read', table_name
      );
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
        and tablename = table_name
        and policyname = table_name || '_admin_write'
    ) then
      execute format(
        'create policy %I on public.%I for all to authenticated using (coalesce((auth.jwt() -> ''app_metadata'' ->> ''site_admin'')::boolean, false)) with check (coalesce((auth.jwt() -> ''app_metadata'' ->> ''site_admin'')::boolean, false))',
        table_name || '_admin_write', table_name
      );
    end if;
  end loop;
end $$;

grant select on table
  public.competitions,
  public.teams,
  public.players,
  public.seasons,
  public.opponents,
  public.opponent_aliases,
  public.player_team_memberships,
  public.series,
  public.matches,
  public.match_player_stats,
  public.league_matches,
  public.scheduled_matches,
  public.playoff_brackets,
  public.playoff_matches
to anon, authenticated;

grant insert, update, delete on table
  public.competitions,
  public.teams,
  public.players,
  public.seasons,
  public.opponents,
  public.opponent_aliases,
  public.player_team_memberships,
  public.series,
  public.matches,
  public.match_player_stats,
  public.league_matches,
  public.scheduled_matches,
  public.playoff_brackets,
  public.playoff_matches
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

comment on table public.seasons is
  'Legacy series grouping retained for compatibility. Permanent V2.4 event archives use competition_seasons.';
comment on table public.player_team_memberships is
  'Time-bounded Flop Reset roster history. Current players.team_id remains the present-team pointer.';

commit;
